#!/bin/bash
# Uninstaller for SUPERTUXKART
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: SUPERTUXKART"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/SuperTuxKart.sh" ]; then
    echo "Removing file: /userdata/roms/ports/SuperTuxKart.sh"
    rm -f "/userdata/roms/ports/SuperTuxKart.sh"
fi
if [ -f "/userdata/roms/ports/images/supertuxkart-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/supertuxkart-logo.png"
    rm -f "/userdata/roms/ports/images/supertuxkart-logo.png"
fi
if [ -f "/userdata/system/add-ons/supertuxkart/SuperTuxKart.tar.xz" ]; then
    echo "Removing file: /userdata/system/add-ons/supertuxkart/SuperTuxKart.tar.xz"
    rm -f "/userdata/system/add-ons/supertuxkart/SuperTuxKart.tar.xz"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/supertuxkart" ]; then
    echo "Removing directory: /userdata/system/add-ons/supertuxkart"
    rm -rf "/userdata/system/add-ons/supertuxkart"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: SUPERTUXKART"
echo "========================================="
