#!/bin/bash
# Uninstaller for ARCADEMANAGER
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: ARCADEMANAGER"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/arcademanager/arcademanager.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/arcademanager/arcademanager.desktop"
    rm -f "/userdata/system/configs/arcademanager/arcademanager.desktop"
fi
if [ -f "/usr/share/applications/arcademanager.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/arcademanager.desktop"
    rm -f "/usr/share/applications/arcademanager.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/arcademanager/arcademanager.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/arcademanager/arcademanager.AppImage"
    rm -f "/userdata/system/add-ons/arcademanager/arcademanager.AppImage"
fi

# Clean up custom.sh entries for ARCADEMANAGER

# Remove installed files
if [ -f "/userdata/system/add-ons/arcademanager/arcademanager.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/arcademanager/arcademanager.AppImage"
    rm -f "/userdata/system/add-ons/arcademanager/arcademanager.AppImage"
fi
if [ -f "/userdata/system/add-ons/arcademanager/extra/arcademanager-icon.png" ]; then
    echo "Removing file: /userdata/system/add-ons/arcademanager/extra/arcademanager-icon.png"
    rm -f "/userdata/system/add-ons/arcademanager/extra/arcademanager-icon.png"
fi
if [ -f "/userdata/system/configs/arcademanager/arcademanager.desktop" ]; then
    echo "Removing file: /userdata/system/configs/arcademanager/arcademanager.desktop"
    rm -f "/userdata/system/configs/arcademanager/arcademanager.desktop"
fi
if [ -f "/userdata/system/configs/arcademanager/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/arcademanager/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/arcademanager/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/arcademanager.desktop" ]; then
    echo "Removing file: /usr/share/applications/arcademanager.desktop"
    rm -f "/usr/share/applications/arcademanager.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/arcademanager" ]; then
    echo "Removing directory: /userdata/system/add-ons/arcademanager"
    rm -rf "/userdata/system/add-ons/arcademanager"
fi
if [ -d "/userdata/system/configs/arcademanager" ]; then
    echo "Removing directory: /userdata/system/configs/arcademanager"
    rm -rf "/userdata/system/configs/arcademanager"
fi

# Update desktop database

echo ""
echo "========================================="
echo "Uninstallation complete: ARCADEMANAGER"
echo "========================================="
