#!/bin/bash
# Uninstaller for ENDLESS-SKY
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: ENDLESS-SKY"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/endless-sky/EndlessSky.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/endless-sky/EndlessSky.AppImage"
    rm -f "/userdata/system/add-ons/endless-sky/EndlessSky.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/EndlessSky.sh" ]; then
    echo "Removing file: /userdata/roms/ports/EndlessSky.sh"
    rm -f "/userdata/roms/ports/EndlessSky.sh"
fi
if [ -f "/userdata/roms/ports/images/endlessskylogo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/endlessskylogo.png"
    rm -f "/userdata/roms/ports/images/endlessskylogo.png"
fi
if [ -f "/userdata/system/add-ons/endless-sky/EndlessSky.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/endless-sky/EndlessSky.AppImage"
    rm -f "/userdata/system/add-ons/endless-sky/EndlessSky.AppImage"
fi
if [ -f "/userdata/system/add-ons/endless-sky/endless-sky-config" ]; then
    echo "Removing file: /userdata/system/add-ons/endless-sky/endless-sky-config"
    rm -f "/userdata/system/add-ons/endless-sky/endless-sky-config"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/endless-sky/endless-sky-config" ]; then
    echo "Removing directory: /userdata/system/add-ons/endless-sky/endless-sky-config"
    rm -rf "/userdata/system/add-ons/endless-sky/endless-sky-config"
fi
if [ -d "/userdata/system/add-ons/endless-sky" ]; then
    echo "Removing directory: /userdata/system/add-ons/endless-sky"
    rm -rf "/userdata/system/add-ons/endless-sky"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: ENDLESS-SKY"
echo "========================================="
