#!/bin/bash
# Uninstaller for SHADPS4
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: SHADPS4"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/add-ons/shadps4/shadps4.desktop" ]; then
    echo "Removing desktop file: /userdata/system/add-ons/shadps4/shadps4.desktop"
    rm -f "/userdata/system/add-ons/shadps4/shadps4.desktop"
fi
if [ -f "/usr/share/applications/shadps4.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/shadps4.desktop"
    rm -f "/usr/share/applications/shadps4.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/shadps4/shadps4plus.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/shadps4/shadps4plus.AppImage"
    rm -f "/userdata/system/add-ons/shadps4/shadps4plus.AppImage"
fi

# Clean up custom.sh entries for SHADPS4

# Remove installed files
if [ -f "/userdata/system/add-ons/shadps4/create_game_launchers.sh" ]; then
    echo "Removing file: /userdata/system/add-ons/shadps4/create_game_launchers.sh"
    rm -f "/userdata/system/add-ons/shadps4/create_game_launchers.sh"
fi
if [ -f "/userdata/system/add-ons/shadps4/extra/shadps4-icon.png" ]; then
    echo "Removing file: /userdata/system/add-ons/shadps4/extra/shadps4-icon.png"
    rm -f "/userdata/system/add-ons/shadps4/extra/shadps4-icon.png"
fi
if [ -f "/userdata/system/add-ons/shadps4/launch_shadps4.sh" ]; then
    echo "Removing file: /userdata/system/add-ons/shadps4/launch_shadps4.sh"
    rm -f "/userdata/system/add-ons/shadps4/launch_shadps4.sh"
fi
if [ -f "/userdata/system/add-ons/shadps4/monitor_shadps4.sh" ]; then
    echo "Removing file: /userdata/system/add-ons/shadps4/monitor_shadps4.sh"
    rm -f "/userdata/system/add-ons/shadps4/monitor_shadps4.sh"
fi
if [ -f "/userdata/system/add-ons/shadps4/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/add-ons/shadps4/restore_desktop_entry.sh"
    rm -f "/userdata/system/add-ons/shadps4/restore_desktop_entry.sh"
fi
if [ -f "/userdata/system/add-ons/shadps4/shadps4.desktop" ]; then
    echo "Removing file: /userdata/system/add-ons/shadps4/shadps4.desktop"
    rm -f "/userdata/system/add-ons/shadps4/shadps4.desktop"
fi
if [ -f "/userdata/system/add-ons/shadps4/shadps4.zip" ]; then
    echo "Removing file: /userdata/system/add-ons/shadps4/shadps4.zip"
    rm -f "/userdata/system/add-ons/shadps4/shadps4.zip"
fi
if [ -f "/usr/share/applications/shadps4.desktop" ]; then
    echo "Removing file: /usr/share/applications/shadps4.desktop"
    rm -f "/usr/share/applications/shadps4.desktop"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/.local/share/shadPS4" ]; then
    echo "Removing directory: /userdata/system/.local/share/shadPS4"
    rm -rf "/userdata/system/.local/share/shadPS4"
fi
if [ -d "/userdata/system/add-ons/shadps4/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/shadps4/extra"
    rm -rf "/userdata/system/add-ons/shadps4/extra"
fi
if [ -d "/userdata/system/add-ons/shadps4" ]; then
    echo "Removing directory: /userdata/system/add-ons/shadps4"
    rm -rf "/userdata/system/add-ons/shadps4"
fi

# Update desktop database

echo ""
echo "========================================="
echo "Uninstallation complete: SHADPS4"
echo "========================================="
