#!/bin/bash
# Uninstaller for ULTRASTAR
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: ULTRASTAR"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/ultrastardeluxe/ultrastardeluxe.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/ultrastardeluxe/ultrastardeluxe.AppImage"
    rm -f "/userdata/system/add-ons/ultrastardeluxe/ultrastardeluxe.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/UltraStarDeluxe.sh" ]; then
    echo "Removing file: /userdata/roms/ports/UltraStarDeluxe.sh"
    rm -f "/userdata/roms/ports/UltraStarDeluxe.sh"
fi
if [ -f "/userdata/roms/ports/images/ultrastardeluxe-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/ports/images/ultrastardeluxe-logo.jpg"
    rm -f "/userdata/roms/ports/images/ultrastardeluxe-logo.jpg"
fi
if [ -f "/userdata/system/add-ons/ultrastardeluxe/ultrastardeluxe.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/ultrastardeluxe/ultrastardeluxe.AppImage"
    rm -f "/userdata/system/add-ons/ultrastardeluxe/ultrastardeluxe.AppImage"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/ultrastardeluxe" ]; then
    echo "Removing directory: /userdata/system/add-ons/ultrastardeluxe"
    rm -rf "/userdata/system/add-ons/ultrastardeluxe"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: ULTRASTAR"
echo "========================================="
