#!/bin/bash
# Uninstaller for AMBERMOON
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: AMBERMOON"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/Ambermoon.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Ambermoon.sh"
    rm -f "/userdata/roms/ports/Ambermoon.sh"
fi
if [ -f "/userdata/roms/ports/images/ambermoon-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/ambermoon-logo.png"
    rm -f "/userdata/roms/ports/images/ambermoon-logo.png"
fi
if [ -f "/userdata/system/add-ons/ambermoon/Ambermoon.tar.gz" ]; then
    echo "Removing file: /userdata/system/add-ons/ambermoon/Ambermoon.tar.gz"
    rm -f "/userdata/system/add-ons/ambermoon/Ambermoon.tar.gz"
fi
if [ -f "/userdata/system/add-ons/ambermoon/ambermoon.cfg" ]; then
    echo "Removing file: /userdata/system/add-ons/ambermoon/ambermoon.cfg"
    rm -f "/userdata/system/add-ons/ambermoon/ambermoon.cfg"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/ambermoon" ]; then
    echo "Removing directory: /userdata/system/add-ons/ambermoon"
    rm -rf "/userdata/system/add-ons/ambermoon"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: AMBERMOON"
echo "========================================="
