#!/bin/bash
# Uninstaller for PORTMASTER
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: PORTMASTER"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/images/portmasterlogo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/portmasterlogo.png"
    rm -f "/userdata/roms/ports/images/portmasterlogo.png"
fi
if [ -f "/userdata/system/add-ons/portmaster/Install.Full.PortMaster.sh" ]; then
    echo "Removing file: /userdata/system/add-ons/portmaster/Install.Full.PortMaster.sh"
    rm -f "/userdata/system/add-ons/portmaster/Install.Full.PortMaster.sh"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/portmaster" ]; then
    echo "Removing directory: /userdata/system/add-ons/portmaster"
    rm -rf "/userdata/system/add-ons/portmaster"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: PORTMASTER"
echo "========================================="
