#!/bin/bash
# Uninstaller for LUTRIS
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: LUTRIS"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/lutris/Lutris.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/lutris/Lutris.desktop"
    rm -f "/userdata/system/configs/lutris/Lutris.desktop"
fi
if [ -f "/usr/share/applications/Lutris.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/Lutris.desktop"
    rm -f "/usr/share/applications/Lutris.desktop"
fi

# Clean up custom.sh entries for LUTRIS

# Remove installed files
if [ -f "/userdata/roms/ports/Lutris.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Lutris.sh"
    rm -f "/userdata/roms/ports/Lutris.sh"
fi
if [ -f "/userdata/roms/ports/Lutris.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/Lutris.sh.keys"
    rm -f "/userdata/roms/ports/Lutris.sh.keys"
fi
if [ -f "/userdata/roms/ports/images/lutrislogo.jpg" ]; then
    echo "Removing file: /userdata/roms/ports/images/lutrislogo.jpg"
    rm -f "/userdata/roms/ports/images/lutrislogo.jpg"
fi
if [ -f "/userdata/system/add-ons/lutris/Launcher" ]; then
    echo "Removing file: /userdata/system/add-ons/lutris/Launcher"
    rm -f "/userdata/system/add-ons/lutris/Launcher"
fi
if [ -f "/userdata/system/add-ons/lutris/lutris.tar.xz" ]; then
    echo "Removing file: /userdata/system/add-ons/lutris/lutris.tar.xz"
    rm -f "/userdata/system/add-ons/lutris/lutris.tar.xz"
fi
if [ -f "/userdata/system/add-ons/lutris/lutris_part_aa" ]; then
    echo "Removing file: /userdata/system/add-ons/lutris/lutris_part_aa"
    rm -f "/userdata/system/add-ons/lutris/lutris_part_aa"
fi
if [ -f "/userdata/system/add-ons/lutris/lutris_part_bb" ]; then
    echo "Removing file: /userdata/system/add-ons/lutris/lutris_part_bb"
    rm -f "/userdata/system/add-ons/lutris/lutris_part_bb"
fi
if [ -f "/userdata/system/configs/lutris/Lutris.desktop" ]; then
    echo "Removing file: /userdata/system/configs/lutris/Lutris.desktop"
    rm -f "/userdata/system/configs/lutris/Lutris.desktop"
fi
if [ -f "/userdata/system/configs/lutris/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/lutris/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/lutris/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/Lutris.desktop" ]; then
    echo "Removing file: /usr/share/applications/Lutris.desktop"
    rm -f "/usr/share/applications/Lutris.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/lutris/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/lutris/extra"
    rm -rf "/userdata/system/add-ons/lutris/extra"
fi
if [ -d "/userdata/system/add-ons/lutris" ]; then
    echo "Removing directory: /userdata/system/add-ons/lutris"
    rm -rf "/userdata/system/add-ons/lutris"
fi
if [ -d "/userdata/system/configs/lutris" ]; then
    echo "Removing directory: /userdata/system/configs/lutris"
    rm -rf "/userdata/system/configs/lutris"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: LUTRIS"
echo "========================================="
