#!/bin/bash
# Uninstaller for STREMIO
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: STREMIO"
echo "========================================="
echo ""

# Uninstall Flatpak applications
if flatpak list --app | grep -q "com.stremio.Stremio" 2>/dev/null; then
    echo "Uninstalling Flatpak app: com.stremio.Stremio"
    flatpak uninstall -y com.stremio.Stremio 2>/dev/null || true
fi

# Remove installed files
if [ -f "/userdata/roms/ports/images/stremio.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/stremio.png"
    rm -f "/userdata/roms/ports/images/stremio.png"
fi
if [ -f "/userdata/roms/ports/stremio.sh" ]; then
    echo "Removing file: /userdata/roms/ports/stremio.sh"
    rm -f "/userdata/roms/ports/stremio.sh"
fi
if [ -f "/userdata/roms/ports/stremio.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/stremio.sh.keys"
    rm -f "/userdata/roms/ports/stremio.sh.keys"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: STREMIO"
echo "========================================="
