#!/bin/bash
# Uninstaller for Maldita Castilla
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Maldita Castilla"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/mc-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/windows/images/mc-logo.jpg"
    rm -f "/userdata/roms/windows/images/mc-logo.jpg"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Maldita Castilla"
echo "========================================="
