#!/bin/bash
# Uninstaller for Crash Bandicoot - Back In Time
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Crash Bandicoot - Back In Time"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/crash-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/windows/images/crash-logo.jpg"
    rm -f "/userdata/roms/windows/images/crash-logo.jpg"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Crash Bandicoot - Back In Time"
echo "========================================="
