#!/bin/bash
# Uninstaller for Celeste
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Celeste"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/celeste-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/windows/images/celeste-logo.jpg"
    rm -f "/userdata/roms/windows/images/celeste-logo.jpg"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Celeste"
echo "========================================="
