#!/bin/bash
# Uninstaller for Super Smash Bros CMC+
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Super Smash Bros CMC+"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/CMC+.wsquashfs" ]; then
    echo "Removing file: /userdata/roms/windows/CMC+.wsquashfs"
    rm -f "/userdata/roms/windows/CMC+.wsquashfs"
fi
if [ -f "/userdata/roms/windows/images/cmc+-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/windows/images/cmc+-logo.jpg"
    rm -f "/userdata/roms/windows/images/cmc+-logo.jpg"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Super Smash Bros CMC+"
echo "========================================="
