#!/bin/bash
# Uninstaller for Donkey Kong Advanced
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Donkey Kong Advanced"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/dka-logo.png" ]; then
    echo "Removing file: /userdata/roms/windows/images/dka-logo.png"
    rm -f "/userdata/roms/windows/images/dka-logo.png"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Donkey Kong Advanced"
echo "========================================="
