#!/bin/bash
# Uninstaller for Modern Modern Chef
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Modern Modern Chef"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/mmc-logo.png" ]; then
    echo "Removing file: /userdata/roms/windows/images/mmc-logo.png"
    rm -f "/userdata/roms/windows/images/mmc-logo.png"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Modern Modern Chef"
echo "========================================="
