#!/bin/bash
# Uninstaller for Spelunky
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Spelunky"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/spelunky-logo.png" ]; then
    echo "Removing file: /userdata/roms/windows/images/spelunky-logo.png"
    rm -f "/userdata/roms/windows/images/spelunky-logo.png"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Spelunky"
echo "========================================="
