#!/bin/bash
# Uninstaller for Space Quest 3D
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Space Quest 3D"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/sq3d-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/windows/images/sq3d-logo.jpg"
    rm -f "/userdata/roms/windows/images/sq3d-logo.jpg"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Space Quest 3D"
echo "========================================="
