#!/bin/bash
# Uninstaller for Sonic Robo Blast 2
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Sonic Robo Blast 2"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/srb2-logo.png" ]; then
    echo "Removing file: /userdata/roms/windows/images/srb2-logo.png"
    rm -f "/userdata/roms/windows/images/srb2-logo.png"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Sonic Robo Blast 2"
echo "========================================="
