#!/bin/bash
# Uninstaller for Super Smash Flash 2
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Super Smash Flash 2"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/ssf2-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/windows/images/ssf2-logo.jpg"
    rm -f "/userdata/roms/windows/images/ssf2-logo.jpg"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Super Smash Flash 2"
echo "========================================="
