#!/bin/bash
# Uninstaller for Sonic Triple Trouble 16bit
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Sonic Triple Trouble 16bit"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/stt-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/windows/images/stt-logo.jpg"
    rm -f "/userdata/roms/windows/images/stt-logo.jpg"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Sonic Triple Trouble 16bit"
echo "========================================="
