#!/bin/bash
# Uninstaller for Zelda - Dungeons of Infinity
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Zelda - Dungeons of Infinity"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/zeldadoi-logo.png" ]; then
    echo "Removing file: /userdata/roms/windows/images/zeldadoi-logo.png"
    rm -f "/userdata/roms/windows/images/zeldadoi-logo.png"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Zelda - Dungeons of Infinity"
echo "========================================="
