#!/bin/bash
# Uninstaller for Zelda 2 PC Remake
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Zelda 2 PC Remake"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/windows/images/zelda2-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/windows/images/zelda2-logo.jpg"
    rm -f "/userdata/roms/windows/images/zelda2-logo.jpg"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: Zelda 2 PC Remake"
echo "========================================="
