#!/bin/bash
# Uninstaller for QBITTORRENT
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: QBITTORRENT"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/add-ons/qbittorrent/extra/qbittorrent.desktop" ]; then
    echo "Removing desktop file: /userdata/system/add-ons/qbittorrent/extra/qbittorrent.desktop"
    rm -f "/userdata/system/add-ons/qbittorrent/extra/qbittorrent.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/qbittorrent/qbittorrent.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/qbittorrent/qbittorrent.AppImage"
    rm -f "/userdata/system/add-ons/qbittorrent/qbittorrent.AppImage"
fi

# Clean up custom.sh entries for QBITTORRENT

# Remove installed files
if [ -f "/userdata/system/add-ons/qbittorrent/extra/icon.png" ]; then
    echo "Removing file: /userdata/system/add-ons/qbittorrent/extra/icon.png"
    rm -f "/userdata/system/add-ons/qbittorrent/extra/icon.png"
fi
if [ -f "/userdata/system/add-ons/qbittorrent/extra/qBittorrent-Enhanced-Edition-x86_64.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/qbittorrent/extra/qBittorrent-Enhanced-Edition-x86_64.AppImage"
    rm -f "/userdata/system/add-ons/qbittorrent/extra/qBittorrent-Enhanced-Edition-x86_64.AppImage"
fi
if [ -f "/userdata/system/add-ons/qbittorrent/extra/qbittorrent.desktop" ]; then
    echo "Removing file: /userdata/system/add-ons/qbittorrent/extra/qbittorrent.desktop"
    rm -f "/userdata/system/add-ons/qbittorrent/extra/qbittorrent.desktop"
fi
if [ -f "/userdata/system/add-ons/qbittorrent/extra/startup.sh" ]; then
    echo "Removing file: /userdata/system/add-ons/qbittorrent/extra/startup.sh"
    rm -f "/userdata/system/add-ons/qbittorrent/extra/startup.sh"
fi
if [ -f "/userdata/system/add-ons/qbittorrent/qbittorrent.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/qbittorrent/qbittorrent.AppImage"
    rm -f "/userdata/system/add-ons/qbittorrent/qbittorrent.AppImage"
fi
if [ -f "/usr/share/applications/qbittorrent.desktop" ]; then
    echo "Removing file: /usr/share/applications/qbittorrent.desktop"
    rm -f "/usr/share/applications/qbittorrent.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/qbittorrent/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/qbittorrent/extra"
    rm -rf "/userdata/system/add-ons/qbittorrent/extra"
fi
if [ -d "/userdata/system/add-ons/qbittorrent" ]; then
    echo "Removing directory: /userdata/system/add-ons/qbittorrent"
    rm -rf "/userdata/system/add-ons/qbittorrent"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: QBITTORRENT"
echo "========================================="
