#!/bin/bash
# Uninstaller for ARMAGETRON
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: ARMAGETRON"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/armagetron/ArmagetronAdvanced.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/armagetron/ArmagetronAdvanced.AppImage"
    rm -f "/userdata/system/add-ons/armagetron/ArmagetronAdvanced.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/Armagetron.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Armagetron.sh"
    rm -f "/userdata/roms/ports/Armagetron.sh"
fi
if [ -f "/userdata/roms/ports/Armagetron.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/Armagetron.sh.keys"
    rm -f "/userdata/roms/ports/Armagetron.sh.keys"
fi
if [ -f "/userdata/roms/ports/images/armagetron-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/armagetron-logo.png"
    rm -f "/userdata/roms/ports/images/armagetron-logo.png"
fi
if [ -f "/userdata/system/add-ons/armagetron/ArmagetronAdvanced.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/armagetron/ArmagetronAdvanced.AppImage"
    rm -f "/userdata/system/add-ons/armagetron/ArmagetronAdvanced.AppImage"
fi
if [ -f "/userdata/system/add-ons/armagetron/armagetron-config" ]; then
    echo "Removing file: /userdata/system/add-ons/armagetron/armagetron-config"
    rm -f "/userdata/system/add-ons/armagetron/armagetron-config"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/armagetron/armagetron-config" ]; then
    echo "Removing directory: /userdata/system/add-ons/armagetron/armagetron-config"
    rm -rf "/userdata/system/add-ons/armagetron/armagetron-config"
fi
if [ -d "/userdata/system/add-ons/armagetron" ]; then
    echo "Removing directory: /userdata/system/add-ons/armagetron"
    rm -rf "/userdata/system/add-ons/armagetron"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: ARMAGETRON"
echo "========================================="
