#!/bin/bash
# Uninstaller for YOUTUBE
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: YOUTUBE"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/YouTubeTV.sh" ]; then
    echo "Removing file: /userdata/roms/ports/YouTubeTV.sh"
    rm -f "/userdata/roms/ports/YouTubeTV.sh"
fi
if [ -f "/userdata/roms/ports/YoutubeTV.sh" ]; then
    echo "Removing file: /userdata/roms/ports/YoutubeTV.sh"
    rm -f "/userdata/roms/ports/YoutubeTV.sh"
fi
if [ -f "/userdata/roms/ports/YoutubeTV.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/YoutubeTV.sh.keys"
    rm -f "/userdata/roms/ports/YoutubeTV.sh.keys"
fi
if [ -f "/userdata/roms/ports/images/youtubetv-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/ports/images/youtubetv-logo.jpg"
    rm -f "/userdata/roms/ports/images/youtubetv-logo.jpg"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/youtube-tv" ]; then
    echo "Removing directory: /userdata/system/add-ons/youtube-tv"
    rm -rf "/userdata/system/add-ons/youtube-tv"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: YOUTUBE"
echo "========================================="
