#!/bin/bash
# Uninstaller for X11VNC
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: X11VNC"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/system/add-ons/x11vnc.tar.gz" ]; then
    echo "Removing file: /userdata/system/add-ons/x11vnc.tar.gz"
    rm -f "/userdata/system/add-ons/x11vnc.tar.gz"
fi
if [ -f "/userdata/system/services/x11vnc" ]; then
    echo "Removing file: /userdata/system/services/x11vnc"
    rm -f "/userdata/system/services/x11vnc"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: X11VNC"
echo "========================================="
