#!/bin/bash
# Uninstaller for F1
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: F1"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/F1.sh" ]; then
    echo "Removing file: /userdata/roms/ports/F1.sh"
    rm -f "/userdata/roms/ports/F1.sh"
fi
if [ -f "/userdata/roms/ports/images/F1-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/ports/images/F1-logo.jpg"
    rm -f "/userdata/roms/ports/images/F1-logo.jpg"
fi
if [ -f "/userdata/tmp/Antimicrox/Antimicrox.DRL" ]; then
    echo "Removing file: /userdata/tmp/Antimicrox/Antimicrox.DRL"
    rm -f "/userdata/tmp/Antimicrox/Antimicrox.DRL"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/tmp/Antimicrox/extracted" ]; then
    echo "Removing directory: /userdata/tmp/Antimicrox/extracted"
    rm -rf "/userdata/tmp/Antimicrox/extracted"
fi
if [ -d "/userdata/tmp/Antimicrox" ]; then
    echo "Removing directory: /userdata/tmp/Antimicrox"
    rm -rf "/userdata/tmp/Antimicrox"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: F1"
echo "========================================="
