#!/bin/bash
# Uninstaller for JDOWNLOADER
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: JDOWNLOADER"
echo "========================================="
echo ""

# Clean up custom.sh entries for JDOWNLOADER

# Remove installed files
if [ -f "/userdata/system/java/microsoft-jdk-17-linux-x64.tar.gz" ]; then
    echo "Removing file: /userdata/system/java/microsoft-jdk-17-linux-x64.tar.gz"
    rm -f "/userdata/system/java/microsoft-jdk-17-linux-x64.tar.gz"
fi
if [ -f "/userdata/system/jdownloader/JDownloader2Setup_unix_nojre.sh" ]; then
    echo "Removing file: /userdata/system/jdownloader/JDownloader2Setup_unix_nojre.sh"
    rm -f "/userdata/system/jdownloader/JDownloader2Setup_unix_nojre.sh"
fi
if [ -f "/userdata/system/jdownloader/jdownloader2" ]; then
    echo "Removing file: /userdata/system/jdownloader/jdownloader2"
    rm -f "/userdata/system/jdownloader/jdownloader2"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/java" ]; then
    echo "Removing directory: /userdata/system/java"
    rm -rf "/userdata/system/java"
fi
if [ -d "/userdata/system/jdownloader" ]; then
    echo "Removing directory: /userdata/system/jdownloader"
    rm -rf "/userdata/system/jdownloader"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: JDOWNLOADER"
echo "========================================="
