#!/bin/bash
# Uninstaller for LUANTI
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: LUANTI"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/luanti/luanti.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/luanti/luanti.AppImage"
    rm -f "/userdata/system/add-ons/luanti/luanti.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/Luanti.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Luanti.sh"
    rm -f "/userdata/roms/ports/Luanti.sh"
fi
if [ -f "/userdata/roms/ports/images/luanti-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/luanti-logo.png"
    rm -f "/userdata/roms/ports/images/luanti-logo.png"
fi
if [ -f "/userdata/system/add-ons/luanti/luanti.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/luanti/luanti.AppImage"
    rm -f "/userdata/system/add-ons/luanti/luanti.AppImage"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/luanti" ]; then
    echo "Removing directory: /userdata/system/add-ons/luanti"
    rm -rf "/userdata/system/add-ons/luanti"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: LUANTI"
echo "========================================="
