#!/bin/bash
# Uninstaller for CUSTOMWINE
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: CUSTOMWINE"
echo "========================================="
echo ""

echo ""
echo "========================================="
echo "Uninstallation complete: CUSTOMWINE"
echo "========================================="
