#!/bin/bash
# Uninstaller for GPARTED
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: GPARTED"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/gparted/gparted.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/gparted/gparted.desktop"
    rm -f "/userdata/system/configs/gparted/gparted.desktop"
fi
if [ -f "/usr/share/applications/gparted.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/gparted.desktop"
    rm -f "/usr/share/applications/gparted.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/gparted/gparted.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/gparted/gparted.AppImage"
    rm -f "/userdata/system/add-ons/gparted/gparted.AppImage"
fi

# Clean up custom.sh entries for GPARTED

# Remove installed files
if [ -f "/userdata/system/add-ons/gparted/extra/gparted-icon.png" ]; then
    echo "Removing file: /userdata/system/add-ons/gparted/extra/gparted-icon.png"
    rm -f "/userdata/system/add-ons/gparted/extra/gparted-icon.png"
fi
if [ -f "/userdata/system/add-ons/gparted/gparted.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/gparted/gparted.AppImage"
    rm -f "/userdata/system/add-ons/gparted/gparted.AppImage"
fi
if [ -f "/userdata/system/configs/gparted/gparted.desktop" ]; then
    echo "Removing file: /userdata/system/configs/gparted/gparted.desktop"
    rm -f "/userdata/system/configs/gparted/gparted.desktop"
fi
if [ -f "/userdata/system/configs/gparted/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/gparted/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/gparted/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/gparted.desktop" ]; then
    echo "Removing file: /usr/share/applications/gparted.desktop"
    rm -f "/usr/share/applications/gparted.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/gparted" ]; then
    echo "Removing directory: /userdata/system/add-ons/gparted"
    rm -rf "/userdata/system/add-ons/gparted"
fi
if [ -d "/userdata/system/configs/gparted" ]; then
    echo "Removing directory: /userdata/system/configs/gparted"
    rm -rf "/userdata/system/configs/gparted"
fi

# Update desktop database

echo ""
echo "========================================="
echo "Uninstallation complete: GPARTED"
echo "========================================="
