#!/bin/bash
# Uninstaller for PLEX
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: PLEX"
echo "========================================="
echo ""

# Uninstall Flatpak applications
if flatpak list --app | grep -q "tv.plex.PlexHTPC" 2>/dev/null; then
    echo "Uninstalling Flatpak app: tv.plex.PlexHTPC"
    flatpak uninstall -y tv.plex.PlexHTPC 2>/dev/null || true
fi

# Remove installed files
if [ -f "/userdata/roms/ports/images/plex.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/plex.png"
    rm -f "/userdata/roms/ports/images/plex.png"
fi
if [ -f "/userdata/roms/ports/plex.sh" ]; then
    echo "Removing file: /userdata/roms/ports/plex.sh"
    rm -f "/userdata/roms/ports/plex.sh"
fi
if [ -f "/userdata/roms/ports/plex.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/plex.sh.keys"
    rm -f "/userdata/roms/ports/plex.sh.keys"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: PLEX"
echo "========================================="
