#!/bin/bash
# Uninstaller for WARZONE2100
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: WARZONE2100"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/Warzone" ]; then
    echo "Removing file: /userdata/roms/ports/Warzone"
    rm -f "/userdata/roms/ports/Warzone"
fi
if [ -f "/userdata/roms/ports/images/warzone 2100-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/warzone 2100-logo.png"
    rm -f "/userdata/roms/ports/images/warzone 2100-logo.png"
fi
if [ -f "/userdata/system/add-ons/warzone 2100/warzone 2100.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/warzone 2100/warzone 2100.AppImage"
    rm -f "/userdata/system/add-ons/warzone 2100/warzone 2100.AppImage"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/warzone 2100" ]; then
    echo "Removing directory: /userdata/system/add-ons/warzone 2100"
    rm -rf "/userdata/system/add-ons/warzone 2100"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: WARZONE2100"
echo "========================================="
