#!/bin/bash
# Uninstaller for EXTRAS
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: EXTRAS"
echo "========================================="
echo ""

# Remove installed files
if [ -f "-" ]; then
    echo "Removing file: -"
    rm -f "-"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/extra" ]; then
    echo "Removing directory: /userdata/extra"
    rm -rf "/userdata/extra"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: EXTRAS"
echo "========================================="
