#!/bin/bash
# Uninstaller for INPUTLEAP
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: INPUTLEAP"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/Desktop/input-leap.desktop" ]; then
    echo "Removing desktop file: /userdata/system/Desktop/input-leap.desktop"
    rm -f "/userdata/system/Desktop/input-leap.desktop"
fi

# Remove installed files
if [ -f "/userdata/system/Desktop/input-leap.desktop" ]; then
    echo "Removing file: /userdata/system/Desktop/input-leap.desktop"
    rm -f "/userdata/system/Desktop/input-leap.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/bua/inputleap" ]; then
    echo "Removing directory: /userdata/system/bua/inputleap"
    rm -rf "/userdata/system/bua/inputleap"
fi
if [ -d "/userdata/system/Desktop" ]; then
    echo "Removing directory: /userdata/system/Desktop"
    rm -rf "/userdata/system/Desktop"
fi

# Update desktop database

echo ""
echo "========================================="
echo "Uninstallation complete: INPUTLEAP"
echo "========================================="
