#!/bin/bash
# Uninstaller for OPENTTD
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: OPENTTD"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/openttd/openttd.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/openttd/openttd.AppImage"
    rm -f "/userdata/system/add-ons/openttd/openttd.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/OpenTTD.sh" ]; then
    echo "Removing file: /userdata/roms/ports/OpenTTD.sh"
    rm -f "/userdata/roms/ports/OpenTTD.sh"
fi
if [ -f "/userdata/roms/ports/images/openttd-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/openttd-logo.png"
    rm -f "/userdata/roms/ports/images/openttd-logo.png"
fi
if [ -f "/userdata/system/add-ons/openttd/openttd.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/openttd/openttd.AppImage"
    rm -f "/userdata/system/add-ons/openttd/openttd.AppImage"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/openttd" ]; then
    echo "Removing directory: /userdata/system/add-ons/openttd"
    rm -rf "/userdata/system/add-ons/openttd"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: OPENTTD"
echo "========================================="
