#!/bin/bash
# Uninstaller for YARG
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: YARG"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/yarg/yarg.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/yarg/yarg.AppImage"
    rm -f "/userdata/system/add-ons/yarg/yarg.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/YARG.sh" ]; then
    echo "Removing file: /userdata/roms/ports/YARG.sh"
    rm -f "/userdata/roms/ports/YARG.sh"
fi
if [ -f "/userdata/roms/ports/images/yarg-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/yarg-logo.png"
    rm -f "/userdata/roms/ports/images/yarg-logo.png"
fi
if [ -f "/userdata/system/add-ons/yarg/yarg.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/yarg/yarg.AppImage"
    rm -f "/userdata/system/add-ons/yarg/yarg.AppImage"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/yarg" ]; then
    echo "Removing directory: /userdata/system/add-ons/yarg"
    rm -rf "/userdata/system/add-ons/yarg"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: YARG"
echo "========================================="
