#!/bin/bash
# Uninstaller for EVEREST
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: EVEREST"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/.local/share/applications/Everest.desktop" ]; then
    echo "Removing desktop file: /userdata/system/.local/share/applications/Everest.desktop"
    rm -f "/userdata/system/.local/share/applications/Everest.desktop"
fi
if [ -f "/userdata/system/Desktop/Everest.desktop" ]; then
    echo "Removing desktop file: /userdata/system/Desktop/Everest.desktop"
    rm -f "/userdata/system/Desktop/Everest.desktop"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/gamelist.xml" ]; then
    echo "Removing file: /userdata/roms/ports/gamelist.xml"
    rm -f "/userdata/roms/ports/gamelist.xml"
fi
if [ -f "/userdata/roms/ports/gamelist.xml.DRL" ]; then
    echo "Removing file: /userdata/roms/ports/gamelist.xml.DRL"
    rm -f "/userdata/roms/ports/gamelist.xml.DRL"
fi
if [ -f "/userdata/system/.local/share/applications/Everest.desktop" ]; then
    echo "Removing file: /userdata/system/.local/share/applications/Everest.desktop"
    rm -f "/userdata/system/.local/share/applications/Everest.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/.local/share/applications" ]; then
    echo "Removing directory: /userdata/system/.local/share/applications"
    rm -rf "/userdata/system/.local/share/applications"
fi

# Update desktop database

echo ""
echo "========================================="
echo "Uninstallation complete: EVEREST"
echo "========================================="
