#!/bin/bash
# Uninstaller for BOTTLES
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: BOTTLES"
echo "========================================="
echo ""

# Uninstall Flatpak applications
if flatpak list --app | grep -q "com.usebottles.bottles" 2>/dev/null; then
    echo "Uninstalling Flatpak app: com.usebottles.bottles"
    flatpak uninstall -y com.usebottles.bottles 2>/dev/null || true
fi

# Remove desktop files
if [ -f "/userdata/system/configs/bottles/bottles.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/bottles/bottles.desktop"
    rm -f "/userdata/system/configs/bottles/bottles.desktop"
fi
if [ -f "/usr/share/applications/bottles.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/bottles.desktop"
    rm -f "/usr/share/applications/bottles.desktop"
fi

# Clean up custom.sh entries for BOTTLES

# Remove installed files
if [ -f "/userdata/system/add-ons/bottles/extra/bottles-icon.png" ]; then
    echo "Removing file: /userdata/system/add-ons/bottles/extra/bottles-icon.png"
    rm -f "/userdata/system/add-ons/bottles/extra/bottles-icon.png"
fi
if [ -f "/userdata/system/configs/bottles/bottles.desktop" ]; then
    echo "Removing file: /userdata/system/configs/bottles/bottles.desktop"
    rm -f "/userdata/system/configs/bottles/bottles.desktop"
fi
if [ -f "/userdata/system/configs/bottles/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/bottles/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/bottles/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/bottles.desktop" ]; then
    echo "Removing file: /usr/share/applications/bottles.desktop"
    rm -f "/usr/share/applications/bottles.desktop"
fi

# Update desktop database


# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/bottles" ]; then
    echo "Removing directory: /userdata/system/add-ons/bottles"
    rm -rf "/userdata/system/add-ons/bottles"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: BOTTLES"
echo "========================================="
