#!/bin/bash
# Uninstaller for STEPMANIA
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: STEPMANIA"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/stepmania/stepmania.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/stepmania/stepmania.AppImage"
    rm -f "/userdata/system/add-ons/stepmania/stepmania.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/Stepmania.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Stepmania.sh"
    rm -f "/userdata/roms/ports/Stepmania.sh"
fi
if [ -f "/userdata/roms/ports/images/stepmania-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/stepmania-logo.png"
    rm -f "/userdata/roms/ports/images/stepmania-logo.png"
fi
if [ -f "/userdata/system/add-ons/stepmania/stepmania.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/stepmania/stepmania.AppImage"
    rm -f "/userdata/system/add-ons/stepmania/stepmania.AppImage"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/stepmania" ]; then
    echo "Removing directory: /userdata/system/add-ons/stepmania"
    rm -rf "/userdata/system/add-ons/stepmania"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: STEPMANIA"
echo "========================================="
