#!/bin/bash
# Uninstaller for CLONEHERO
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: CLONEHERO"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/add-ons/clonehero/extra/clonehero.desktop" ]; then
    echo "Removing desktop file: /userdata/system/add-ons/clonehero/extra/clonehero.desktop"
    rm -f "/userdata/system/add-ons/clonehero/extra/clonehero.desktop"
fi

# Clean up custom.sh entries for CLONEHERO

# Remove installed files
if [ -f "//userdata/system/add-ons/clonehero/extra/icon.png" ]; then
    echo "Removing file: //userdata/system/add-ons/clonehero/extra/icon.png"
    rm -f "//userdata/system/add-ons/clonehero/extra/icon.png"
fi
if [ -f "/tmp/clonehero_download/clonehero.tar.xz" ]; then
    echo "Removing file: /tmp/clonehero_download/clonehero.tar.xz"
    rm -f "/tmp/clonehero_download/clonehero.tar.xz"
fi
if [ -f "/userdata/roms/ports/images/CloneHero_Logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/CloneHero_Logo.png"
    rm -f "/userdata/roms/ports/images/CloneHero_Logo.png"
fi
if [ -f "/userdata/system/add-ons/clonehero/extra/clonehero.desktop" ]; then
    echo "Removing file: /userdata/system/add-ons/clonehero/extra/clonehero.desktop"
    rm -f "/userdata/system/add-ons/clonehero/extra/clonehero.desktop"
fi
if [ -f "/userdata/system/add-ons/clonehero/extra/startup" ]; then
    echo "Removing file: /userdata/system/add-ons/clonehero/extra/startup"
    rm -f "/userdata/system/add-ons/clonehero/extra/startup"
fi
if [ -f "/usr/share/applications/clonehero.desktop" ]; then
    echo "Removing file: /usr/share/applications/clonehero.desktop"
    rm -f "/usr/share/applications/clonehero.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/clonehero/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/clonehero/extra"
    rm -rf "/userdata/system/add-ons/clonehero/extra"
fi
if [ -d "/userdata/system/add-ons/clonehero" ]; then
    echo "Removing directory: /userdata/system/add-ons/clonehero"
    rm -rf "/userdata/system/add-ons/clonehero"
fi
if [ -d "/tmp/clonehero_download" ]; then
    echo "Removing directory: /tmp/clonehero_download"
    rm -rf "/tmp/clonehero_download"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: CLONEHERO"
echo "========================================="
