#!/bin/bash
# Uninstaller for CSPORTABLE
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: CSPORTABLE"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/CSPortable.sh" ]; then
    echo "Removing file: /userdata/roms/ports/CSPortable.sh"
    rm -f "/userdata/roms/ports/CSPortable.sh"
fi
if [ -f "/userdata/roms/ports/images/cs-portable-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/ports/images/cs-portable-logo.jpg"
    rm -f "/userdata/roms/ports/images/cs-portable-logo.jpg"
fi
if [ -f "/userdata/system/add-ons/csportable/CS-Portable-2023.zip" ]; then
    echo "Removing file: /userdata/system/add-ons/csportable/CS-Portable-2023.zip"
    rm -f "/userdata/system/add-ons/csportable/CS-Portable-2023.zip"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/csportable" ]; then
    echo "Removing directory: /userdata/system/add-ons/csportable"
    rm -rf "/userdata/system/add-ons/csportable"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: CSPORTABLE"
echo "========================================="
