#!/bin/bash
# Uninstaller for SOAR
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: SOAR"
echo "========================================="
echo ""

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/soar/bin" ]; then
    echo "Removing directory: /userdata/system/add-ons/soar/bin"
    rm -rf "/userdata/system/add-ons/soar/bin"
fi
if [ -d "/userdata/system/.config/soar" ]; then
    echo "Removing directory: /userdata/system/.config/soar"
    rm -rf "/userdata/system/.config/soar"
fi
if [ -d "/userdata/system/add-ons/soar" ]; then
    echo "Removing directory: /userdata/system/add-ons/soar"
    rm -rf "/userdata/system/add-ons/soar"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: SOAR"
echo "========================================="
