#!/bin/bash
# Uninstaller for 7ZIP
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: 7ZIP"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/add-ons/7zip/extra/7zip.desktop" ]; then
    echo "Removing desktop file: /userdata/system/add-ons/7zip/extra/7zip.desktop"
    rm -f "/userdata/system/add-ons/7zip/extra/7zip.desktop"
fi

# Clean up custom.sh entries for 7ZIP

# Remove installed files
if [ -f "/userdata/system/add-ons/7zip/extra/7zip.desktop" ]; then
    echo "Removing file: /userdata/system/add-ons/7zip/extra/7zip.desktop"
    rm -f "/userdata/system/add-ons/7zip/extra/7zip.desktop"
fi
if [ -f "/userdata/system/add-ons/7zip/extra/7zip.zip" ]; then
    echo "Removing file: /userdata/system/add-ons/7zip/extra/7zip.zip"
    rm -f "/userdata/system/add-ons/7zip/extra/7zip.zip"
fi
if [ -f "/userdata/system/add-ons/7zip/extra/icon.png" ]; then
    echo "Removing file: /userdata/system/add-ons/7zip/extra/icon.png"
    rm -f "/userdata/system/add-ons/7zip/extra/icon.png"
fi
if [ -f "/userdata/system/add-ons/7zip/extra/startup.sh" ]; then
    echo "Removing file: /userdata/system/add-ons/7zip/extra/startup.sh"
    rm -f "/userdata/system/add-ons/7zip/extra/startup.sh"
fi
if [ -f "/usr/share/applications/7zip.desktop" ]; then
    echo "Removing file: /usr/share/applications/7zip.desktop"
    rm -f "/usr/share/applications/7zip.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/7zip/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/7zip/extra"
    rm -rf "/userdata/system/add-ons/7zip/extra"
fi
if [ -d "/userdata/system/add-ons/7zip" ]; then
    echo "Removing directory: /userdata/system/add-ons/7zip"
    rm -rf "/userdata/system/add-ons/7zip"
fi

# Update desktop database

echo ""
echo "========================================="
echo "Uninstallation complete: 7ZIP"
echo "========================================="
