#!/bin/bash
# Uninstaller for Alpine XFCE (Webtop)
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Alpine XFCE (Webtop)"
echo "========================================="
echo ""

# Stop and remove Docker containers
if docker ps -a --format '{{.Names}}' | grep -q "^alpine-xfce$" 2>/dev/null; then
    echo "Stopping Docker container: alpine-xfce"
    docker stop "alpine-xfce" 2>/dev/null || true
    echo "Removing Docker container: alpine-xfce"
    docker rm "alpine-xfce" 2>/dev/null || true
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/alpine xfce/home" ]; then
    echo "Removing directory: /userdata/system/add-ons/alpine xfce/home"
    rm -rf "/userdata/system/add-ons/alpine xfce/home"
fi
if [ -d "/userdata/system/add-ons/alpine xfce" ]; then
    echo "Removing directory: /userdata/system/add-ons/alpine xfce"
    rm -rf "/userdata/system/add-ons/alpine xfce"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: Alpine XFCE (Webtop)"
echo "========================================="
