#!/bin/bash
# Uninstaller for Arch KDE (Webtop)
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Arch KDE (Webtop)"
echo "========================================="
echo ""

# Stop and remove Docker containers
if docker ps -a --format '{{.Names}}' | grep -q "^arch-kde$" 2>/dev/null; then
    echo "Stopping Docker container: arch-kde"
    docker stop "arch-kde" 2>/dev/null || true
    echo "Removing Docker container: arch-kde"
    docker rm "arch-kde" 2>/dev/null || true
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/arch kde/home" ]; then
    echo "Removing directory: /userdata/system/add-ons/arch kde/home"
    rm -rf "/userdata/system/add-ons/arch kde/home"
fi
if [ -d "/userdata/system/add-ons/arch kde" ]; then
    echo "Removing directory: /userdata/system/add-ons/arch kde"
    rm -rf "/userdata/system/add-ons/arch kde"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: Arch KDE (Webtop)"
echo "========================================="
