#!/bin/bash
# Uninstaller for Arr-In-One
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Arr-In-One"
echo "========================================="
echo ""

# Stop and remove Docker containers
if docker ps -a --format '{{.Names}}' | grep -q "^arr-in-one$" 2>/dev/null; then
    echo "Stopping Docker container: arr-in-one"
    docker stop "arr-in-one" 2>/dev/null || true
    echo "Removing Docker container: arr-in-one"
    docker rm "arr-in-one" 2>/dev/null || true
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/arrinone/config" ]; then
    echo "Removing directory: /userdata/system/add-ons/arrinone/config"
    rm -rf "/userdata/system/add-ons/arrinone/config"
fi
if [ -d "/userdata/system/add-ons/arrinone/downloads" ]; then
    echo "Removing directory: /userdata/system/add-ons/arrinone/downloads"
    rm -rf "/userdata/system/add-ons/arrinone/downloads"
fi
if [ -d "/userdata/system/add-ons/arrinone/movies" ]; then
    echo "Removing directory: /userdata/system/add-ons/arrinone/movies"
    rm -rf "/userdata/system/add-ons/arrinone/movies"
fi
if [ -d "/userdata/system/add-ons/arrinone/music" ]; then
    echo "Removing directory: /userdata/system/add-ons/arrinone/music"
    rm -rf "/userdata/system/add-ons/arrinone/music"
fi
if [ -d "/userdata/system/add-ons/arrinone/tv" ]; then
    echo "Removing directory: /userdata/system/add-ons/arrinone/tv"
    rm -rf "/userdata/system/add-ons/arrinone/tv"
fi
if [ -d "/userdata/system/add-ons/arrinone" ]; then
    echo "Removing directory: /userdata/system/add-ons/arrinone"
    rm -rf "/userdata/system/add-ons/arrinone"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: Arr-In-One"
echo "========================================="
