#!/bin/bash
# Uninstaller for CasaOS
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: CasaOS"
echo "========================================="
echo ""

# Stop and remove Docker containers
if docker ps -a --format '{{.Names}}' | grep -q "^casa$" 2>/dev/null; then
    echo "Stopping Docker container: casa"
    docker stop "casa" 2>/dev/null || true
    echo "Removing Docker container: casa"
    docker rm "casa" 2>/dev/null || true
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/casaos" ]; then
    echo "Removing directory: /userdata/system/add-ons/casaos"
    rm -rf "/userdata/system/add-ons/casaos"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: CasaOS"
echo "========================================="
