#!/bin/bash
# Uninstaller for CLITOOLS
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: CLITOOLS"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/system/cli.tar.xz" ]; then
    echo "Removing file: /userdata/system/cli.tar.xz"
    rm -f "/userdata/system/cli.tar.xz"
fi

# Remove created directories (deepest first)

echo ""
echo "========================================="
echo "Uninstallation complete: CLITOOLS"
echo "========================================="
