#!/bin/bash
# Uninstaller for Emby
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Emby"
echo "========================================="
echo ""

# Stop and remove Docker containers
if docker ps -a --format '{{.Names}}' | grep -q "^emby$" 2>/dev/null; then
    echo "Stopping Docker container: emby"
    docker stop "emby" 2>/dev/null || true
    echo "Removing Docker container: emby"
    docker rm "emby" 2>/dev/null || true
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/emby/data/movies" ]; then
    echo "Removing directory: /userdata/system/add-ons/emby/data/movies"
    rm -rf "/userdata/system/add-ons/emby/data/movies"
fi
if [ -d "/userdata/system/add-ons/emby/data/tvshows" ]; then
    echo "Removing directory: /userdata/system/add-ons/emby/data/tvshows"
    rm -rf "/userdata/system/add-ons/emby/data/tvshows"
fi
if [ -d "/userdata/system/add-ons/emby/config" ]; then
    echo "Removing directory: /userdata/system/add-ons/emby/config"
    rm -rf "/userdata/system/add-ons/emby/config"
fi
if [ -d "/userdata/system/add-ons/emby" ]; then
    echo "Removing directory: /userdata/system/add-ons/emby"
    rm -rf "/userdata/system/add-ons/emby"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: Emby"
echo "========================================="
