#!/bin/bash
# Uninstaller for Jellyfin
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Jellyfin"
echo "========================================="
echo ""

# Stop and remove Docker containers
if docker ps -a --format '{{.Names}}' | grep -q "^jellyfin$" 2>/dev/null; then
    echo "Stopping Docker container: jellyfin"
    docker stop "jellyfin" 2>/dev/null || true
    echo "Removing Docker container: jellyfin"
    docker rm "jellyfin" 2>/dev/null || true
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/jellyfin/data/movies" ]; then
    echo "Removing directory: /userdata/system/add-ons/jellyfin/data/movies"
    rm -rf "/userdata/system/add-ons/jellyfin/data/movies"
fi
if [ -d "/userdata/system/add-ons/jellyfin/data/tvshows" ]; then
    echo "Removing directory: /userdata/system/add-ons/jellyfin/data/tvshows"
    rm -rf "/userdata/system/add-ons/jellyfin/data/tvshows"
fi
if [ -d "/userdata/system/add-ons/jellyfin/config" ]; then
    echo "Removing directory: /userdata/system/add-ons/jellyfin/config"
    rm -rf "/userdata/system/add-ons/jellyfin/config"
fi
if [ -d "/userdata/system/add-ons/jellyfin" ]; then
    echo "Removing directory: /userdata/system/add-ons/jellyfin"
    rm -rf "/userdata/system/add-ons/jellyfin"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: Jellyfin"
echo "========================================="
