#!/bin/bash
# Uninstaller for Ubuntu MATE (Webtop)
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: Ubuntu MATE (Webtop)"
echo "========================================="
echo ""

# Stop and remove Docker containers
if docker ps -a --format '{{.Names}}' | grep -q "^ubuntu-mate$" 2>/dev/null; then
    echo "Stopping Docker container: ubuntu-mate"
    docker stop "ubuntu-mate" 2>/dev/null || true
    echo "Removing Docker container: ubuntu-mate"
    docker rm "ubuntu-mate" 2>/dev/null || true
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/ubuntu mate/home" ]; then
    echo "Removing directory: /userdata/system/add-ons/ubuntu mate/home"
    rm -rf "/userdata/system/add-ons/ubuntu mate/home"
fi
if [ -d "/userdata/system/add-ons/ubuntu mate" ]; then
    echo "Removing directory: /userdata/system/add-ons/ubuntu mate"
    rm -rf "/userdata/system/add-ons/ubuntu mate"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: Ubuntu MATE (Webtop)"
echo "========================================="
