#!/bin/bash
# Uninstaller for UmbrelOS
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: UmbrelOS"
echo "========================================="
echo ""

# Stop and remove Docker containers
if docker ps -a --format '{{.Names}}' | grep -q "^umbrel$" 2>/dev/null; then
    echo "Stopping Docker container: umbrel"
    docker stop "umbrel" 2>/dev/null || true
    echo "Removing Docker container: umbrel"
    docker rm "umbrel" 2>/dev/null || true
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/umbrel" ]; then
    echo "Removing directory: /userdata/system/add-ons/umbrel"
    rm -rf "/userdata/system/add-ons/umbrel"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: UmbrelOS"
echo "========================================="
