#!/bin/bash
# Uninstaller for DESKTOP_FOR_BATOCERA
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: DESKTOP_FOR_BATOCERA"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/overlay/overlay/usr/share/applications/CoreKeyboard.desktop" ]; then
    echo "Removing desktop file: /overlay/overlay/usr/share/applications/CoreKeyboard.desktop"
    rm -f "/overlay/overlay/usr/share/applications/CoreKeyboard.desktop"
fi
if [ -f "/userdata/system/Desktop/VLC.desktop" ]; then
    echo "Removing desktop file: /userdata/system/Desktop/VLC.desktop"
    rm -f "/userdata/system/Desktop/VLC.desktop"
fi
if [ -f "/userdata/system/Desktop/gparted.desktop" ]; then
    echo "Removing desktop file: /userdata/system/Desktop/gparted.desktop"
    rm -f "/userdata/system/Desktop/gparted.desktop"
fi
if [ -f "/userdata/system/Desktop/vlc.desktop" ]; then
    echo "Removing desktop file: /userdata/system/Desktop/vlc.desktop"
    rm -f "/userdata/system/Desktop/vlc.desktop"
fi

# Remove installed files
if [ -f "/userdata/system/Desktop/CoreKeyboard.desktop" ]; then
    echo "Removing file: /userdata/system/Desktop/CoreKeyboard.desktop"
    rm -f "/userdata/system/Desktop/CoreKeyboard.desktop"
fi
if [ -f "/userdata/tmp/Desktop_for_Batocera/Desktop_for_Batocera.DRL" ]; then
    echo "Removing file: /userdata/tmp/Desktop_for_Batocera/Desktop_for_Batocera.DRL"
    rm -f "/userdata/tmp/Desktop_for_Batocera/Desktop_for_Batocera.DRL"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/tmp/Desktop_for_Batocera/extracted" ]; then
    echo "Removing directory: /userdata/tmp/Desktop_for_Batocera/extracted"
    rm -rf "/userdata/tmp/Desktop_for_Batocera/extracted"
fi
if [ -d "/userdata/tmp/Desktop_for_Batocera" ]; then
    echo "Removing directory: /userdata/tmp/Desktop_for_Batocera"
    rm -rf "/userdata/tmp/Desktop_for_Batocera"
fi

# Update desktop database
if [ -d "/userdata/system/configs/bat-drl/Remover_Desktop.sh" ]; then
    echo "Running the official uninstaller: /userdata/system/configs/bat-drl/Remover_Desktop.sh"
    /userdata/system/configs/bat-drl/Remover_Desktop.sh
fi

echo ""
echo "========================================="
echo "Uninstallation complete: DESKTOP_FOR_BATOCERA"
echo "========================================="
