#!/bin/bash
# Uninstaller for SWITCH
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: SWITCH"
echo "========================================="
echo ""

echo ""
echo "========================================="
echo "Uninstallation complete: SWITCH"
echo "========================================="
