#!/bin/bash
# Uninstaller for CHIAKI
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: CHIAKI"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/chiaki/chiaki.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/chiaki/chiaki.desktop"
    rm -f "/userdata/system/configs/chiaki/chiaki.desktop"
fi
if [ -f "/usr/share/applications/chiaki.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/chiaki.desktop"
    rm -f "/usr/share/applications/chiaki.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/chiaki/Chiaki.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/chiaki/Chiaki.AppImage"
    rm -f "/userdata/system/add-ons/chiaki/Chiaki.AppImage"
fi

# Clean up custom.sh entries for CHIAKI

# Remove installed files
if [ -f "/userdata/roms/ports/Chiaki.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Chiaki.sh"
    rm -f "/userdata/roms/ports/Chiaki.sh"
fi
if [ -f "/userdata/roms/ports/images/chiakilogo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/chiakilogo.png"
    rm -f "/userdata/roms/ports/images/chiakilogo.png"
fi
if [ -f "/userdata/system/add-ons/chiaki/Chiaki.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/chiaki/Chiaki.AppImage"
    rm -f "/userdata/system/add-ons/chiaki/Chiaki.AppImage"
fi
if [ -f "/userdata/system/configs/chiaki/chiaki.desktop" ]; then
    echo "Removing file: /userdata/system/configs/chiaki/chiaki.desktop"
    rm -f "/userdata/system/configs/chiaki/chiaki.desktop"
fi
if [ -f "/userdata/system/configs/chiaki/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/chiaki/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/chiaki/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/chiaki.desktop" ]; then
    echo "Removing file: /usr/share/applications/chiaki.desktop"
    rm -f "/usr/share/applications/chiaki.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/chiaki/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/chiaki/extra"
    rm -rf "/userdata/system/add-ons/chiaki/extra"
fi
if [ -d "/userdata/system/add-ons/chiaki" ]; then
    echo "Removing directory: /userdata/system/add-ons/chiaki"
    rm -rf "/userdata/system/add-ons/chiaki"
fi
if [ -d "/userdata/system/configs/chiaki" ]; then
    echo "Removing directory: /userdata/system/configs/chiaki"
    rm -rf "/userdata/system/configs/chiaki"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: CHIAKI"
echo "========================================="
