#!/bin/bash
# Uninstaller for TIDAL
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: TIDAL"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/Tidal" ]; then
    echo "Removing file: /userdata/roms/ports/Tidal"
    rm -f "/userdata/roms/ports/Tidal"
fi
if [ -f "/userdata/roms/ports/images/tidal hifi-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/ports/images/tidal hifi-logo.jpg"
    rm -f "/userdata/roms/ports/images/tidal hifi-logo.jpg"
fi
if [ -f "/userdata/system/add-ons/tidal hifi/tidal hifi.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/tidal hifi/tidal hifi.AppImage"
    rm -f "/userdata/system/add-ons/tidal hifi/tidal hifi.AppImage"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/tidal hifi" ]; then
    echo "Removing directory: /userdata/system/add-ons/tidal hifi"
    rm -rf "/userdata/system/add-ons/tidal hifi"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: TIDAL"
echo "========================================="
