#!/bin/bash
# Uninstaller for DISNEYPLUS
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: DISNEYPLUS"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/DisneyPlus.sh" ]; then
    echo "Removing file: /userdata/roms/ports/DisneyPlus.sh"
    rm -f "/userdata/roms/ports/DisneyPlus.sh"
fi
if [ -f "/userdata/roms/ports/DisneyPlus.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/DisneyPlus.sh.keys"
    rm -f "/userdata/roms/ports/DisneyPlus.sh.keys"
fi
if [ -f "/userdata/roms/ports/images/disneyplus-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/disneyplus-logo.png"
    rm -f "/userdata/roms/ports/images/disneyplus-logo.png"
fi
if [ -f "/userdata/system/add-ons/google-chrome/chrome.sh" ]; then
    echo "Removing file: /userdata/system/add-ons/google-chrome/chrome.sh"
    rm -f "/userdata/system/add-ons/google-chrome/chrome.sh"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/google-chrome" ]; then
    echo "Removing directory: /userdata/system/add-ons/google-chrome"
    rm -rf "/userdata/system/add-ons/google-chrome"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: DISNEYPLUS"
echo "========================================="
