#!/bin/bash
# Uninstaller for JAVA-RUNTIME
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: JAVA-RUNTIME"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/add-ons/java/extra/java.desktop" ]; then
    echo "Removing desktop file: /userdata/system/add-ons/java/extra/java.desktop"
    rm -f "/userdata/system/add-ons/java/extra/java.desktop"
fi

# Clean up custom.sh entries for JAVA-RUNTIME

# Remove installed files
if [ -f "/userdata/system/add-ons/java/Launcher" ]; then
    echo "Removing file: /userdata/system/add-ons/java/Launcher"
    rm -f "/userdata/system/add-ons/java/Launcher"
fi
if [ -f "/userdata/system/add-ons/java/extra/downloads/java.tar.gz" ]; then
    echo "Removing file: /userdata/system/add-ons/java/extra/downloads/java.tar.gz"
    rm -f "/userdata/system/add-ons/java/extra/downloads/java.tar.gz"
fi
if [ -f "/userdata/system/add-ons/java/extra/java.desktop" ]; then
    echo "Removing file: /userdata/system/add-ons/java/extra/java.desktop"
    rm -f "/userdata/system/add-ons/java/extra/java.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/java/extra/downloads" ]; then
    echo "Removing directory: /userdata/system/add-ons/java/extra/downloads"
    rm -rf "/userdata/system/add-ons/java/extra/downloads"
fi
if [ -d "/userdata/system/add-ons/java/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/java/extra"
    rm -rf "/userdata/system/add-ons/java/extra"
fi
if [ -d "/userdata/system/add-ons/java/home" ]; then
    echo "Removing directory: /userdata/system/add-ons/java/home"
    rm -rf "/userdata/system/add-ons/java/home"
fi
if [ -d "/userdata/system/add-ons/java" ]; then
    echo "Removing directory: /userdata/system/add-ons/java"
    rm -rf "/userdata/system/add-ons/java"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: JAVA-RUNTIME"
echo "========================================="
