#!/bin/bash
# Uninstaller for MOONLIGHT
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: MOONLIGHT"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/moonlight/moonlight.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/moonlight/moonlight.AppImage"
    rm -f "/userdata/system/add-ons/moonlight/moonlight.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/Moonlight.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Moonlight.sh"
    rm -f "/userdata/roms/ports/Moonlight.sh"
fi
if [ -f "/userdata/roms/ports/images/moonlightlogo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/moonlightlogo.png"
    rm -f "/userdata/roms/ports/images/moonlightlogo.png"
fi
if [ -f "/userdata/system/add-ons/moonlight/moonlight-config" ]; then
    echo "Removing file: /userdata/system/add-ons/moonlight/moonlight-config"
    rm -f "/userdata/system/add-ons/moonlight/moonlight-config"
fi
if [ -f "/userdata/system/add-ons/moonlight/moonlight.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/moonlight/moonlight.AppImage"
    rm -f "/userdata/system/add-ons/moonlight/moonlight.AppImage"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/moonlight/moonlight-config" ]; then
    echo "Removing directory: /userdata/system/add-ons/moonlight/moonlight-config"
    rm -rf "/userdata/system/add-ons/moonlight/moonlight-config"
fi
if [ -d "/userdata/system/add-ons/moonlight" ]; then
    echo "Removing directory: /userdata/system/add-ons/moonlight"
    rm -rf "/userdata/system/add-ons/moonlight"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: MOONLIGHT"
echo "========================================="
