#!/bin/bash
# Uninstaller for VESKTOP
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: VESKTOP"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/vesktop/Vesktop.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/vesktop/Vesktop.desktop"
    rm -f "/userdata/system/configs/vesktop/Vesktop.desktop"
fi
if [ -f "/usr/share/applications/Vesktop.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/Vesktop.desktop"
    rm -f "/usr/share/applications/Vesktop.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/vesktop/Vesktop.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/vesktop/Vesktop.AppImage"
    rm -f "/userdata/system/add-ons/vesktop/Vesktop.AppImage"
fi

# Clean up custom.sh entries for VESKTOP

# Remove installed files
if [ -f "/userdata/roms/ports/Vesktop.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Vesktop.sh"
    rm -f "/userdata/roms/ports/Vesktop.sh"
fi
if [ -f "/userdata/roms/ports/Vesktop.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/Vesktop.sh.keys"
    rm -f "/userdata/roms/ports/Vesktop.sh.keys"
fi
if [ -f "/userdata/roms/ports/images/vesktoplogo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/vesktoplogo.png"
    rm -f "/userdata/roms/ports/images/vesktoplogo.png"
fi
if [ -f "/userdata/system/add-ons/vesktop/Vesktop.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/vesktop/Vesktop.AppImage"
    rm -f "/userdata/system/add-ons/vesktop/Vesktop.AppImage"
fi
if [ -f "/userdata/system/configs/vesktop/Vesktop.desktop" ]; then
    echo "Removing file: /userdata/system/configs/vesktop/Vesktop.desktop"
    rm -f "/userdata/system/configs/vesktop/Vesktop.desktop"
fi
if [ -f "/userdata/system/configs/vesktop/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/vesktop/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/vesktop/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/Vesktop.desktop" ]; then
    echo "Removing file: /usr/share/applications/Vesktop.desktop"
    rm -f "/usr/share/applications/Vesktop.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/vesktop/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/vesktop/extra"
    rm -rf "/userdata/system/add-ons/vesktop/extra"
fi
if [ -d "/userdata/system/add-ons/vesktop" ]; then
    echo "Removing directory: /userdata/system/add-ons/vesktop"
    rm -rf "/userdata/system/add-ons/vesktop"
fi
if [ -d "/userdata/system/configs/vesktop" ]; then
    echo "Removing directory: /userdata/system/configs/vesktop"
    rm -rf "/userdata/system/configs/vesktop"
fi
fi

# Update desktop database

echo ""
echo "========================================="
echo "Uninstallation complete: VESKTOP"
echo "========================================="
