#!/bin/bash
# Uninstaller for AMAZON-LUNA
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: AMAZON-LUNA"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/AmazonLuna.sh" ]; then
    echo "Removing file: /userdata/roms/ports/AmazonLuna.sh"
    rm -f "/userdata/roms/ports/AmazonLuna.sh"
fi
if [ -f "/userdata/roms/ports/images/amazonluna.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/amazonluna.png"
    rm -f "/userdata/roms/ports/images/amazonluna.png"
fi
if [ -f "/userdata/system/add-ons/amazonluna/*" ]; then
    echo "Removing file: /userdata/system/add-ons/amazonluna/*"
    rm -f "/userdata/system/add-ons/amazonluna/*"
fi
if [ -f "/userdata/system/add-ons/amazonluna/temp/amazonluna.tar.xz" ]; then
    echo "Removing file: /userdata/system/add-ons/amazonluna/temp/amazonluna.tar.xz"
    rm -f "/userdata/system/add-ons/amazonluna/temp/amazonluna.tar.xz"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/amazonluna/config" ]; then
    echo "Removing directory: /userdata/system/add-ons/amazonluna/config"
    rm -rf "/userdata/system/add-ons/amazonluna/config"
fi
if [ -d "/userdata/system/add-ons/amazonluna/home" ]; then
    echo "Removing directory: /userdata/system/add-ons/amazonluna/home"
    rm -rf "/userdata/system/add-ons/amazonluna/home"
fi
if [ -d "/userdata/system/add-ons/amazonluna/roms" ]; then
    echo "Removing directory: /userdata/system/add-ons/amazonluna/roms"
    rm -rf "/userdata/system/add-ons/amazonluna/roms"
fi
if [ -d "/userdata/system/add-ons/amazonluna/temp" ]; then
    echo "Removing directory: /userdata/system/add-ons/amazonluna/temp"
    rm -rf "/userdata/system/add-ons/amazonluna/temp"
fi
if [ -d "/userdata/system/add-ons/amazonluna" ]; then
    echo "Removing directory: /userdata/system/add-ons/amazonluna"
    rm -rf "/userdata/system/add-ons/amazonluna"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: AMAZON-LUNA"
echo "========================================="
