#!/bin/bash
# Uninstaller for BRAVE
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: BRAVE"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/brave/brave.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/brave/brave.AppImage"
    rm -f "/userdata/system/add-ons/brave/brave.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/Brave.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Brave.sh"
    rm -f "/userdata/roms/ports/Brave.sh"
fi
if [ -f "/userdata/roms/ports/images/brave-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/brave-logo.png"
    rm -f "/userdata/roms/ports/images/brave-logo.png"
fi
if [ -f "/userdata/system/add-ons/brave/brave.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/brave/brave.AppImage"
    rm -f "/userdata/system/add-ons/brave/brave.AppImage"
fi
if [ -f "releases" ]; then
    echo "Removing file: releases"
    rm -f "releases"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/brave" ]; then
    echo "Removing directory: /userdata/system/add-ons/brave"
    rm -rf "/userdata/system/add-ons/brave"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: BRAVE"
echo "========================================="
