#!/bin/bash
# Uninstaller for FREETUBE
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: FREETUBE"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/freetube/freetube.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/freetube/freetube.AppImage"
    rm -f "/userdata/system/add-ons/freetube/freetube.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/FreeTube.sh" ]; then
    echo "Removing file: /userdata/roms/ports/FreeTube.sh"
    rm -f "/userdata/roms/ports/FreeTube.sh"
fi
if [ -f "/userdata/roms/ports/FreeTube.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/FreeTube.sh.keys"
    rm -f "/userdata/roms/ports/FreeTube.sh.keys"
fi
if [ -f "/userdata/roms/ports/images/freetube-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/freetube-logo.png"
    rm -f "/userdata/roms/ports/images/freetube-logo.png"
fi
if [ -f "/userdata/system/add-ons/freetube/freetube.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/freetube/freetube.AppImage"
    rm -f "/userdata/system/add-ons/freetube/freetube.AppImage"
fi
if [ -f "releases" ]; then
    echo "Removing file: releases"
    rm -f "releases"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/freetube" ]; then
    echo "Removing directory: /userdata/system/add-ons/freetube"
    rm -rf "/userdata/system/add-ons/freetube"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: FREETUBE"
echo "========================================="
