#!/bin/bash
# Uninstaller for CHROME
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: CHROME"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/chrome/Chrome.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/chrome/Chrome.desktop"
    rm -f "/userdata/system/configs/chrome/Chrome.desktop"
fi
if [ -f "/usr/share/applications/Chrome.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/Chrome.desktop"
    rm -f "/usr/share/applications/Chrome.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/google-chrome/GoogleChrome.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/google-chrome/GoogleChrome.AppImage"
    rm -f "/userdata/system/add-ons/google-chrome/GoogleChrome.AppImage"
fi

# Clean up custom.sh entries for CHROME

# Remove installed files
if [ -f "/userdata/roms/ports/GoogleChrome.sh" ]; then
    echo "Removing file: /userdata/roms/ports/GoogleChrome.sh"
    rm -f "/userdata/roms/ports/GoogleChrome.sh"
fi
if [ -f "/userdata/roms/ports/images/chrome-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/chrome-logo.png"
    rm -f "/userdata/roms/ports/images/chrome-logo.png"
fi
if [ -f "/userdata/system/add-ons/google-chrome/GoogleChrome.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/google-chrome/GoogleChrome.AppImage"
    rm -f "/userdata/system/add-ons/google-chrome/GoogleChrome.AppImage"
fi
if [ -f "/userdata/system/configs/chrome/Chrome.desktop" ]; then
    echo "Removing file: /userdata/system/configs/chrome/Chrome.desktop"
    rm -f "/userdata/system/configs/chrome/Chrome.desktop"
fi
if [ -f "/userdata/system/configs/chrome/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/chrome/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/chrome/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/Chrome.desktop" ]; then
    echo "Removing file: /usr/share/applications/Chrome.desktop"
    rm -f "/usr/share/applications/Chrome.desktop"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/google-chrome/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/google-chrome/extra"
    rm -rf "/userdata/system/add-ons/google-chrome/extra"
fi
if [ -d "/userdata/system/add-ons/google-chrome" ]; then
    echo "Removing directory: /userdata/system/add-ons/google-chrome"
    rm -rf "/userdata/system/add-ons/google-chrome"
fi
if [ -d "/userdata/system/configs/chrome" ]; then
    echo "Removing directory: /userdata/system/configs/chrome"
    rm -rf "/userdata/system/configs/chrome"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: CHROME"
echo "========================================="
