#!/bin/bash
# Uninstaller for ASSAULTCUBE
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: ASSAULTCUBE"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/AssaultCube.sh" ]; then
    echo "Removing file: /userdata/roms/ports/AssaultCube.sh"
    rm -f "/userdata/roms/ports/AssaultCube.sh"
fi
if [ -f "/userdata/roms/ports/images/assaultcube-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/assaultcube-logo.png"
    rm -f "/userdata/roms/ports/images/assaultcube-logo.png"
fi
if [ -f "/userdata/system/add-ons/assaultcube/AssaultCube.tar.bz2" ]; then
    echo "Removing file: /userdata/system/add-ons/assaultcube/AssaultCube.tar.bz2"
    rm -f "/userdata/system/add-ons/assaultcube/AssaultCube.tar.bz2"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/assaultcube" ]; then
    echo "Removing directory: /userdata/system/add-ons/assaultcube"
    rm -rf "/userdata/system/add-ons/assaultcube"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: ASSAULTCUBE"
echo "========================================="
