#!/bin/bash
# Uninstaller for PEAZIP
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: PEAZIP"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/peazip/PeaZip.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/peazip/PeaZip.desktop"
    rm -f "/userdata/system/configs/peazip/PeaZip.desktop"
fi
if [ -f "/usr/share/applications/PeaZip.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/PeaZip.desktop"
    rm -f "/usr/share/applications/PeaZip.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/peazip/peazip.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/peazip/peazip.AppImage"
    rm -f "/userdata/system/add-ons/peazip/peazip.AppImage"
fi

# Clean up custom.sh entries for PEAZIP

# Remove installed files
if [ -f "/userdata/system/add-ons/peazip/extra/icon.png" ]; then
    echo "Removing file: /userdata/system/add-ons/peazip/extra/icon.png"
    rm -f "/userdata/system/add-ons/peazip/extra/icon.png"
fi
if [ -f "/userdata/system/add-ons/peazip/peazip.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/peazip/peazip.AppImage"
    rm -f "/userdata/system/add-ons/peazip/peazip.AppImage"
fi
if [ -f "/userdata/system/configs/peazip/PeaZip.desktop" ]; then
    echo "Removing file: /userdata/system/configs/peazip/PeaZip.desktop"
    rm -f "/userdata/system/configs/peazip/PeaZip.desktop"
fi
if [ -f "/userdata/system/configs/peazip/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/peazip/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/peazip/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/PeaZip.desktop" ]; then
    echo "Removing file: /usr/share/applications/PeaZip.desktop"
    rm -f "/usr/share/applications/PeaZip.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/peazip/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/peazip/extra"
    rm -rf "/userdata/system/add-ons/peazip/extra"
fi
if [ -d "/userdata/system/add-ons/peazip" ]; then
    echo "Removing directory: /userdata/system/add-ons/peazip"
    rm -rf "/userdata/system/add-ons/peazip"
fi
if [ -d "/userdata/system/configs/peazip" ]; then
    echo "Removing directory: /userdata/system/configs/peazip"
    rm -rf "/userdata/system/configs/peazip"
fi

# Update desktop database

echo ""
echo "========================================="
echo "Uninstallation complete: PEAZIP"
echo "========================================="
