#!/bin/bash
# Uninstaller for STEAM
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: STEAM"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/steam/Steam.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/steam/Steam.desktop"
    rm -f "/userdata/system/configs/steam/Steam.desktop"
fi
if [ -f "/usr/share/applications/Steam.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/Steam.desktop"
    rm -f "/usr/share/applications/Steam.desktop"
fi

# Clean up custom.sh entries for STEAM

# Remove installed files
if [ -f "/userdata/roms/ports/Steam.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Steam.sh"
    rm -f "/userdata/roms/ports/Steam.sh"
fi
if [ -f "/userdata/roms/ports/Steam.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/Steam.sh.keys"
    rm -f "/userdata/roms/ports/Steam.sh.keys"
fi
if [ -f "/userdata/roms/ports/images/steamlogo.jpg" ]; then
    echo "Removing file: /userdata/roms/ports/images/steamlogo.jpg"
    rm -f "/userdata/roms/ports/images/steamlogo.jpg"
fi
if [ -f "/userdata/system/add-ons/steam/Launcher" ]; then
    echo "Removing file: /userdata/system/add-ons/steam/Launcher"
    rm -f "/userdata/system/add-ons/steam/Launcher"
fi
if [ -f "/userdata/system/add-ons/steam/steam_part_aa" ]; then
    echo "Removing file: /userdata/system/add-ons/steam/steam_part_aa"
    rm -f "/userdata/system/add-ons/steam/steam_part_aa"
fi
if [ -f "/userdata/system/add-ons/steam/steam_part_ab" ]; then
    echo "Removing file: /userdata/system/add-ons/steam/steam_part_ab"
    rm -f "/userdata/system/add-ons/steam/steam_part_ab"
fi
if [ -f "/userdata/system/configs/steam/Steam.desktop" ]; then
    echo "Removing file: /userdata/system/configs/steam/Steam.desktop"
    rm -f "/userdata/system/configs/steam/Steam.desktop"
fi
if [ -f "/userdata/system/configs/steam/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/steam/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/steam/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/Steam.desktop" ]; then
    echo "Removing file: /usr/share/applications/Steam.desktop"
    rm -f "/usr/share/applications/Steam.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/steam/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/steam/extra"
    rm -rf "/userdata/system/add-ons/steam/extra"
fi
if [ -d "/userdata/system/add-ons/steam" ]; then
    echo "Removing directory: /userdata/system/add-ons/steam"
    rm -rf "/userdata/system/add-ons/steam"
fi
if [ -d "/userdata/system/configs/steam" ]; then
    echo "Removing directory: /userdata/system/configs/steam"
    rm -rf "/userdata/system/configs/steam"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: STEAM"
echo "========================================="
