#!/bin/bash
# Uninstaller for OPENRGB
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: OPENRGB"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/openrgb/OpenRGB.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/openrgb/OpenRGB.desktop"
    rm -f "/userdata/system/configs/openrgb/OpenRGB.desktop"
fi
if [ -f "/usr/share/applications/OpenRGB.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/OpenRGB.desktop"
    rm -f "/usr/share/applications/OpenRGB.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/openrgb/openrgb.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/openrgb/openrgb.AppImage"
    rm -f "/userdata/system/add-ons/openrgb/openrgb.AppImage"
fi

# Clean up custom.sh entries for OPENRGB

# Remove installed files
if [ -f "/userdata/system/add-ons/openrgb/openrgb.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/openrgb/openrgb.AppImage"
    rm -f "/userdata/system/add-ons/openrgb/openrgb.AppImage"
fi
if [ -f "/userdata/system/configs/openrgb/OpenRGB.desktop" ]; then
    echo "Removing file: /userdata/system/configs/openrgb/OpenRGB.desktop"
    rm -f "/userdata/system/configs/openrgb/OpenRGB.desktop"
fi
if [ -f "/userdata/system/configs/openrgb/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/openrgb/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/openrgb/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/OpenRGB.desktop" ]; then
    echo "Removing file: /usr/share/applications/OpenRGB.desktop"
    rm -f "/usr/share/applications/OpenRGB.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/openrgb/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/openrgb/extra"
    rm -rf "/userdata/system/add-ons/openrgb/extra"
fi
if [ -d "/userdata/system/add-ons/openrgb" ]; then
    echo "Removing directory: /userdata/system/add-ons/openrgb"
    rm -rf "/userdata/system/add-ons/openrgb"
fi
if [ -d "/userdata/system/configs/openrgb" ]; then
    echo "Removing directory: /userdata/system/configs/openrgb"
    rm -rf "/userdata/system/configs/openrgb"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: OPENRGB"
echo "========================================="
