#!/bin/bash
# Uninstaller for OBS
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: OBS"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/obs/obs.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/obs/obs.desktop"
    rm -f "/userdata/system/configs/obs/obs.desktop"
fi
if [ -f "/usr/share/applications/obs.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/obs.desktop"
    rm -f "/usr/share/applications/obs.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/obs/obs.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/obs/obs.AppImage"
    rm -f "/userdata/system/add-ons/obs/obs.AppImage"
fi

# Clean up custom.sh entries for OBS

# Remove installed files
if [ -f "/userdata/system/add-ons/obs/extra/obs-icon.png" ]; then
    echo "Removing file: /userdata/system/add-ons/obs/extra/obs-icon.png"
    rm -f "/userdata/system/add-ons/obs/extra/obs-icon.png"
fi
if [ -f "/userdata/system/add-ons/obs/obs.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/obs/obs.AppImage"
    rm -f "/userdata/system/add-ons/obs/obs.AppImage"
fi
if [ -f "/userdata/system/configs/obs/obs.desktop" ]; then
    echo "Removing file: /userdata/system/configs/obs/obs.desktop"
    rm -f "/userdata/system/configs/obs/obs.desktop"
fi
if [ -f "/userdata/system/configs/obs/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/obs/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/obs/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/obs.desktop" ]; then
    echo "Removing file: /usr/share/applications/obs.desktop"
    rm -f "/usr/share/applications/obs.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/obs" ]; then
    echo "Removing directory: /userdata/system/add-ons/obs"
    rm -rf "/userdata/system/add-ons/obs"
fi
if [ -d "/userdata/system/configs/obs" ]; then
    echo "Removing directory: /userdata/system/configs/obs"
    rm -rf "/userdata/system/configs/obs"
fi

# Update desktop database

echo ""
echo "========================================="
echo "Uninstallation complete: OBS"
echo "========================================="
