#!/bin/bash
# Uninstaller for BRIDGE
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: BRIDGE"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/bridge/bridge.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/bridge/bridge.desktop"
    rm -f "/userdata/system/configs/bridge/bridge.desktop"
fi
if [ -f "/usr/share/applications/bridge.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/bridge.desktop"
    rm -f "/usr/share/applications/bridge.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/bridge/bridge.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/bridge/bridge.AppImage"
    rm -f "/userdata/system/add-ons/bridge/bridge.AppImage"
fi

# Clean up custom.sh entries for BRIDGE

# Remove installed files
if [ -f "/userdata/system/add-ons/bridge/bridge.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/bridge/bridge.AppImage"
    rm -f "/userdata/system/add-ons/bridge/bridge.AppImage"
fi
if [ -f "/userdata/system/add-ons/bridge/extra/bridge-icon.png" ]; then
    echo "Removing file: /userdata/system/add-ons/bridge/extra/bridge-icon.png"
    rm -f "/userdata/system/add-ons/bridge/extra/bridge-icon.png"
fi
if [ -f "/userdata/system/configs/bridge/bridge.desktop" ]; then
    echo "Removing file: /userdata/system/configs/bridge/bridge.desktop"
    rm -f "/userdata/system/configs/bridge/bridge.desktop"
fi
if [ -f "/userdata/system/configs/bridge/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/bridge/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/bridge/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/bridge.desktop" ]; then
    echo "Removing file: /usr/share/applications/bridge.desktop"
    rm -f "/usr/share/applications/bridge.desktop"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/bridge" ]; then
    echo "Removing directory: /userdata/system/add-ons/bridge"
    rm -rf "/userdata/system/add-ons/bridge"
fi
if [ -d "/userdata/system/configs/bridge" ]; then
    echo "Removing directory: /userdata/system/configs/bridge"
    rm -rf "/userdata/system/configs/bridge"
fi

# Update desktop database

echo ""
echo "========================================="
echo "Uninstallation complete: BRIDGE"
echo "========================================="
