#!/bin/bash
# Uninstaller for TAILSCALE
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: TAILSCALE"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/etc/sysctl.conf" ]; then
    echo "Removing file: /etc/sysctl.conf"
    rm -f "/etc/sysctl.conf"
fi
if [ -f "/etc/sysctl.conf.bak" ]; then
    echo "Removing file: /etc/sysctl.conf.bak"
    rm -f "/etc/sysctl.conf.bak"
fi
if [ -f "/tmp/sysctl.conf" ]; then
    echo "Removing file: /tmp/sysctl.conf"
    rm -f "/tmp/sysctl.conf"
fi
if [ -f "/userdata/system/add-ons/tailscale/systemd" ]; then
    echo "Removing file: /userdata/system/add-ons/tailscale/systemd"
    rm -f "/userdata/system/add-ons/tailscale/systemd"
fi
if [ -f "/userdata/system/add-ons/tailscale/tailscale" ]; then
    echo "Removing file: /userdata/system/add-ons/tailscale/tailscale"
    rm -f "/userdata/system/add-ons/tailscale/tailscale"
fi
if [ -f "/userdata/system/add-ons/tailscale/tailscaled" ]; then
    echo "Removing file: /userdata/system/add-ons/tailscale/tailscaled"
    rm -f "/userdata/system/add-ons/tailscale/tailscaled"
fi
if [ -f "/userdata/system/services/tailscale" ]; then
    echo "Removing file: /userdata/system/services/tailscale"
    rm -f "/userdata/system/services/tailscale"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/tailscale" ]; then
    echo "Removing directory: /userdata/system/add-ons/tailscale"
    rm -rf "/userdata/system/add-ons/tailscale"
fi
if [ -d "/dev/net" ]; then
    echo "Removing directory: /dev/net"
    rm -rf "/dev/net"
fi
if [ -d "/userdata/temp" ]; then
    echo "Removing directory: /userdata/temp"
    rm -rf "/userdata/temp"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: TAILSCALE"
echo "========================================="
