#!/bin/bash
# Uninstaller for FLATHUB
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: FLATHUB"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/flathub.sh" ]; then
    echo "Removing file: /userdata/roms/ports/flathub.sh"
    rm -f "/userdata/roms/ports/flathub.sh"
fi
if [ -f "/userdata/roms/ports/flathub.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/flathub.sh.keys"
    rm -f "/userdata/roms/ports/flathub.sh.keys"
fi
if [ -f "/userdata/roms/ports/images/flathub-logo.jpg" ]; then
    echo "Removing file: /userdata/roms/ports/images/flathub-logo.jpg"
    rm -f "/userdata/roms/ports/images/flathub-logo.jpg"
fi
if [ -f "/userdata/system/add-ons/google-chrome/chrome.sh" ]; then
    echo "Removing file: /userdata/system/add-ons/google-chrome/chrome.sh"
    rm -f "/userdata/system/add-ons/google-chrome/chrome.sh"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/google-chrome" ]; then
    echo "Removing directory: /userdata/system/add-ons/google-chrome"
    rm -rf "/userdata/system/add-ons/google-chrome"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: FLATHUB"
echo "========================================="
