#!/bin/bash
# Uninstaller for FREEDROIDRPG
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: FREEDROIDRPG"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/freedroidrpg/freedroidrpg.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/freedroidrpg/freedroidrpg.AppImage"
    rm -f "/userdata/system/add-ons/freedroidrpg/freedroidrpg.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/FreedroidRPG.sh" ]; then
    echo "Removing file: /userdata/roms/ports/FreedroidRPG.sh"
    rm -f "/userdata/roms/ports/FreedroidRPG.sh"
fi
if [ -f "/userdata/roms/ports/images/freedroidrpg-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/freedroidrpg-logo.png"
    rm -f "/userdata/roms/ports/images/freedroidrpg-logo.png"
fi
if [ -f "/userdata/system/add-ons/freedroidrpg/freedroidrpg.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/freedroidrpg/freedroidrpg.AppImage"
    rm -f "/userdata/system/add-ons/freedroidrpg/freedroidrpg.AppImage"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/freedroidrpg" ]; then
    echo "Removing directory: /userdata/system/add-ons/freedroidrpg"
    rm -rf "/userdata/system/add-ons/freedroidrpg"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: FREEDROIDRPG"
echo "========================================="
