#!/bin/bash
# Uninstaller for FIREFOX
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: FIREFOX"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/firefox/Firefox.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/firefox/Firefox.desktop"
    rm -f "/userdata/system/configs/firefox/Firefox.desktop"
fi
if [ -f "/usr/share/applications/Firefox.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/Firefox.desktop"
    rm -f "/usr/share/applications/Firefox.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/firefox/Firefox.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/firefox/Firefox.AppImage"
    rm -f "/userdata/system/add-ons/firefox/Firefox.AppImage"
fi

# Clean up custom.sh entries for FIREFOX

# Remove installed files
if [ -f "/userdata/roms/ports/Firefox.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Firefox.sh"
    rm -f "/userdata/roms/ports/Firefox.sh"
fi
if [ -f "/userdata/roms/ports/images/firefox-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/firefox-logo.png"
    rm -f "/userdata/roms/ports/images/firefox-logo.png"
fi
if [ -f "/userdata/system/add-ons/firefox/Firefox.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/firefox/Firefox.AppImage"
    rm -f "/userdata/system/add-ons/firefox/Firefox.AppImage"
fi
if [ -f "/userdata/system/configs/firefox/Firefox.desktop" ]; then
    echo "Removing file: /userdata/system/configs/firefox/Firefox.desktop"
    rm -f "/userdata/system/configs/firefox/Firefox.desktop"
fi
if [ -f "/userdata/system/configs/firefox/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/firefox/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/firefox/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/Firefox.desktop" ]; then
    echo "Removing file: /usr/share/applications/Firefox.desktop"
    rm -f "/usr/share/applications/Firefox.desktop"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/firefox/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/firefox/extra"
    rm -rf "/userdata/system/add-ons/firefox/extra"
fi
if [ -d "/userdata/system/add-ons/firefox" ]; then
    echo "Removing directory: /userdata/system/add-ons/firefox"
    rm -rf "/userdata/system/add-ons/firefox"
fi
if [ -d "/userdata/system/configs/firefox" ]; then
    echo "Removing directory: /userdata/system/configs/firefox"
    rm -rf "/userdata/system/configs/firefox"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: FIREFOX"
echo "========================================="
