#!/bin/bash
# Uninstaller for SUPERTUX
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: SUPERTUX"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/supertux/supertux.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/supertux/supertux.AppImage"
    rm -f "/userdata/system/add-ons/supertux/supertux.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/SuperTux.sh" ]; then
    echo "Removing file: /userdata/roms/ports/SuperTux.sh"
    rm -f "/userdata/roms/ports/SuperTux.sh"
fi
if [ -f "/userdata/roms/ports/images/supertux-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/supertux-logo.png"
    rm -f "/userdata/roms/ports/images/supertux-logo.png"
fi
if [ -f "/userdata/system/add-ons/supertux/supertux.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/supertux/supertux.AppImage"
    rm -f "/userdata/system/add-ons/supertux/supertux.AppImage"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/supertux" ]; then
    echo "Removing directory: /userdata/system/add-ons/supertux"
    rm -rf "/userdata/system/add-ons/supertux"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: SUPERTUX"
echo "========================================="
