#!/bin/bash
# Uninstaller for QEMU-GA
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: QEMU-GA"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/system/services/qemu_ga" ]; then
    echo "Removing file: /userdata/system/services/qemu_ga"
    rm -f "/userdata/system/services/qemu_ga"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/qga" ]; then
    echo "Removing directory: /userdata/system/add-ons/qga"
    rm -rf "/userdata/system/add-ons/qga"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: QEMU-GA"
echo "========================================="
