#!/bin/bash
# Uninstaller for FILEZILLA
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: FILEZILLA"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/filezilla/FileZilla.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/filezilla/FileZilla.desktop"
    rm -f "/userdata/system/configs/filezilla/FileZilla.desktop"
fi
if [ -f "/usr/share/applications/FileZilla.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/FileZilla.desktop"
    rm -f "/usr/share/applications/FileZilla.desktop"
fi

# Clean up custom.sh entries for FILEZILLA

# Remove installed files
if [ -f "/userdata/system/add-ons/filezilla/FileZilla_3.68.1_x86_64-linux-gnu.tar.xz" ]; then
    echo "Removing file: /userdata/system/add-ons/filezilla/FileZilla_3.68.1_x86_64-linux-gnu.tar.xz"
    rm -f "/userdata/system/add-ons/filezilla/FileZilla_3.68.1_x86_64-linux-gnu.tar.xz"
fi
if [ -f "/userdata/system/configs/filezilla/FileZilla.desktop" ]; then
    echo "Removing file: /userdata/system/configs/filezilla/FileZilla.desktop"
    rm -f "/userdata/system/configs/filezilla/FileZilla.desktop"
fi
if [ -f "/userdata/system/configs/filezilla/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/filezilla/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/filezilla/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/FileZilla.desktop" ]; then
    echo "Removing file: /usr/share/applications/FileZilla.desktop"
    rm -f "/usr/share/applications/FileZilla.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/filezilla/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/filezilla/extra"
    rm -rf "/userdata/system/add-ons/filezilla/extra"
fi
if [ -d "/userdata/system/add-ons/filezilla" ]; then
    echo "Removing directory: /userdata/system/add-ons/filezilla"
    rm -rf "/userdata/system/add-ons/filezilla"
fi
if [ -d "/userdata/system/configs/filezilla" ]; then
    echo "Removing directory: /userdata/system/configs/filezilla"
    rm -rf "/userdata/system/configs/filezilla"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: FILEZILLA"
echo "========================================="
