#!/bin/bash
# Uninstaller for GREENLIGHT
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: GREENLIGHT"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/greenlight/Greenlight.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/greenlight/Greenlight.desktop"
    rm -f "/userdata/system/configs/greenlight/Greenlight.desktop"
fi
if [ -f "/usr/share/applications/Greenlight.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/Greenlight.desktop"
    rm -f "/usr/share/applications/Greenlight.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/greenlight/temp/greenlight.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/greenlight/temp/greenlight.AppImage"
    rm -f "/userdata/system/add-ons/greenlight/temp/greenlight.AppImage"
fi
if [ -f "/userdata/system/add-ons/greenlight/greenlight.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/greenlight/greenlight.AppImage"
    rm -f "/userdata/system/add-ons/greenlight/greenlight.AppImage"
fi

# Clean up custom.sh entries for GREENLIGHT

# Remove installed files
if [ -f "/userdata/roms/ports/Greenlight.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Greenlight.sh"
    rm -f "/userdata/roms/ports/Greenlight.sh"
fi
if [ -f "/userdata/roms/ports/images/greenlight.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/greenlight.png"
    rm -f "/userdata/roms/ports/images/greenlight.png"
fi
if [ -f "/userdata/system/add-ons/greenlight/greenlight.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/greenlight/greenlight.AppImage"
    rm -f "/userdata/system/add-ons/greenlight/greenlight.AppImage"
fi
if [ -f "/userdata/system/add-ons/greenlight/temp/greenlight.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/greenlight/temp/greenlight.AppImage"
    rm -f "/userdata/system/add-ons/greenlight/temp/greenlight.AppImage"
fi
if [ -f "/userdata/system/configs/greenlight/Greenlight.desktop" ]; then
    echo "Removing file: /userdata/system/configs/greenlight/Greenlight.desktop"
    rm -f "/userdata/system/configs/greenlight/Greenlight.desktop"
fi
if [ -f "/userdata/system/configs/greenlight/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/greenlight/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/greenlight/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/Greenlight.desktop" ]; then
    echo "Removing file: /usr/share/applications/Greenlight.desktop"
    rm -f "/usr/share/applications/Greenlight.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/greenlight/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/greenlight/extra"
    rm -rf "/userdata/system/add-ons/greenlight/extra"
fi
if [ -d "/userdata/system/add-ons/greenlight/temp" ]; then
    echo "Removing directory: /userdata/system/add-ons/greenlight/temp"
    rm -rf "/userdata/system/add-ons/greenlight/temp"
fi
if [ -d "/userdata/system/add-ons/greenlight" ]; then
    echo "Removing directory: /userdata/system/add-ons/greenlight"
    rm -rf "/userdata/system/add-ons/greenlight"
fi
if [ -d "/userdata/system/configs/greenlight" ]; then
    echo "Removing directory: /userdata/system/configs/greenlight"
    rm -rf "/userdata/system/configs/greenlight"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: GREENLIGHT"
echo "========================================="
