#!/bin/bash
# Uninstaller for MINECRAFT
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: MINECRAFT"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/minecraft/minecraftbedrock/Minecraft_Launcher.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/minecraft/minecraftbedrock/Minecraft_Launcher.AppImage"
    rm -f "/userdata/system/add-ons/minecraft/minecraftbedrock/Minecraft_Launcher.AppImage"
fi
if [ -f "/userdata/system/add-ons/minecraft/minecraftbedrock/Minecraft_Launcher.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/minecraft/minecraftbedrock/Minecraft_Launcher.AppImage"
    rm -f "/userdata/system/add-ons/minecraft/minecraftbedrock/Minecraft_Launcher.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/Minecraft.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Minecraft.sh"
    rm -f "/userdata/roms/ports/Minecraft.sh"
fi
if [ -f "/userdata/roms/ports/MinecraftBedrock.sh" ]; then
    echo "Removing file: /userdata/roms/ports/MinecraftBedrock.sh"
    rm -f "/userdata/roms/ports/MinecraftBedrock.sh"
fi
if [ -f "/userdata/roms/ports/MinecraftJava.sh" ]; then
    echo "Removing file: /userdata/roms/ports/MinecraftJava.sh"
    rm -f "/userdata/roms/ports/MinecraftJava.sh"
fi
if [ -f "/userdata/roms/ports/images/Minecraft Bedrock Edition-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/Minecraft Bedrock Edition-logo.png"
    rm -f "/userdata/roms/ports/images/Minecraft Bedrock Edition-logo.png"
fi
if [ -f "/userdata/system/add-ons/minecraft/minecraftbedrock/Minecraft_Launcher.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/minecraft/minecraftbedrock/Minecraft_Launcher.AppImage"
    rm -f "/userdata/system/add-ons/minecraft/minecraftbedrock/Minecraft_Launcher.AppImage"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/minecraft/minecraftbedrock/minecraft-config" ]; then
    echo "Removing directory: /userdata/system/add-ons/minecraft/minecraftbedrock/minecraft-config"
    rm -rf "/userdata/system/add-ons/minecraft/minecraftbedrock/minecraft-config"
fi
if [ -d "/userdata/system/add-ons/minecraft/minecraftbedrock" ]; then
    echo "Removing directory: /userdata/system/add-ons/minecraft/minecraftbedrock"
    rm -rf "/userdata/system/add-ons/minecraft/minecraftbedrock"
fi
if [ -d "/userdata/system/add-ons/minecraft" ]; then
    echo "Removing directory: /userdata/system/add-ons/minecraft"
    rm -rf "/userdata/system/add-ons/minecraft"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: MINECRAFT"
echo "========================================="
