#!/bin/bash
# Uninstaller for XONOTIC
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: XONOTIC"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/Xonotic.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Xonotic.sh"
    rm -f "/userdata/roms/ports/Xonotic.sh"
fi
if [ -f "/userdata/roms/ports/images/xonotic-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/xonotic-logo.png"
    rm -f "/userdata/roms/ports/images/xonotic-logo.png"
fi
if [ -f "/userdata/system/add-ons/xonotic/xonotic.zip" ]; then
    echo "Removing file: /userdata/system/add-ons/xonotic/xonotic.zip"
    rm -f "/userdata/system/add-ons/xonotic/xonotic.zip"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/xonotic" ]; then
    echo "Removing directory: /userdata/system/add-ons/xonotic"
    rm -rf "/userdata/system/add-ons/xonotic"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: XONOTIC"
echo "========================================="
