#!/bin/bash
# Uninstaller for SUPERMARIOX
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: SUPERMARIOX"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/SuperMarioX.sh" ]; then
    echo "Removing file: /userdata/roms/ports/SuperMarioX.sh"
    rm -f "/userdata/roms/ports/SuperMarioX.sh"
fi
if [ -f "/userdata/roms/ports/images/supermariox-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/supermariox-logo.png"
    rm -f "/userdata/roms/ports/images/supermariox-logo.png"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/mariox" ]; then
    echo "Removing directory: /userdata/system/add-ons/mariox"
    rm -rf "/userdata/system/add-ons/mariox"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: SUPERMARIOX"
echo "========================================="
