#!/bin/bash
# Uninstaller for IPTVNATOR
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: IPTVNATOR"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/iptvnator/IPTVNator.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/iptvnator/IPTVNator.AppImage"
    rm -f "/userdata/system/add-ons/iptvnator/IPTVNator.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/IPTVNator.sh" ]; then
    echo "Removing file: /userdata/roms/ports/IPTVNator.sh"
    rm -f "/userdata/roms/ports/IPTVNator.sh"
fi
if [ -f "/userdata/roms/ports/IPTVNator.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/IPTVNator.sh.keys"
    rm -f "/userdata/roms/ports/IPTVNator.sh.keys"
fi
if [ -f "/userdata/roms/ports/images/iptvnator-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/iptvnator-logo.png"
    rm -f "/userdata/roms/ports/images/iptvnator-logo.png"
fi
if [ -f "/userdata/system/add-ons/iptvnator/IPTVNator.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/iptvnator/IPTVNator.AppImage"
    rm -f "/userdata/system/add-ons/iptvnator/IPTVNator.AppImage"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/iptvnator" ]; then
    echo "Removing directory: /userdata/system/add-ons/iptvnator"
    rm -rf "/userdata/system/add-ons/iptvnator"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: IPTVNATOR"
echo "========================================="
