#!/bin/bash
# Uninstaller for CONTY
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: CONTY"
echo "========================================="
echo ""

# Remove symlinks
if [ -L "/usr/bin/conty" ]; then
    echo "Removing symlink: /usr/bin/conty"
    rm -f "/usr/bin/conty"
fi

# Remove installed files
if [ -f "/userdata/system/add-ons/conty/bin/conty.sh" ]; then
    echo "Removing file: /userdata/system/add-ons/conty/bin/conty.sh"
    rm -f "/userdata/system/add-ons/conty/bin/conty.sh"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/conty/bin" ]; then
    echo "Removing directory: /userdata/system/add-ons/conty/bin"
    rm -rf "/userdata/system/add-ons/conty/bin"
fi
if [ -d "/userdata/system/add-ons/conty" ]; then
    echo "Removing directory: /userdata/system/add-ons/conty"
    rm -rf "/userdata/system/add-ons/conty"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: CONTY"
echo "========================================="
