#!/bin/bash
# Uninstaller for OPENRA
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: OPENRA"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/openra/openra.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/openra/openra.AppImage"
    rm -f "/userdata/system/add-ons/openra/openra.AppImage"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/OpenRA.sh" ]; then
    echo "Removing file: /userdata/roms/ports/OpenRA.sh"
    rm -f "/userdata/roms/ports/OpenRA.sh"
fi
if [ -f "/userdata/roms/ports/images/openra-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/openra-logo.png"
    rm -f "/userdata/roms/ports/images/openra-logo.png"
fi
if [ -f "/userdata/system/add-ons/openra/openra.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/openra/openra.AppImage"
    rm -f "/userdata/system/add-ons/openra/openra.AppImage"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/openra" ]; then
    echo "Removing directory: /userdata/system/add-ons/openra"
    rm -rf "/userdata/system/add-ons/openra"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: OPENRA"
echo "========================================="
