#!/bin/bash
# Uninstaller for FIGHTCADE
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: FIGHTCADE"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/Fightcade.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Fightcade.sh"
    rm -f "/userdata/roms/ports/Fightcade.sh"
fi
if [ -f "/userdata/roms/ports/images/fightcade-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/fightcade-logo.png"
    rm -f "/userdata/roms/ports/images/fightcade-logo.png"
fi
if [ -f "/userdata/system/add-ons/fightcade/Fightcade-linux-latest.tar.gz" ]; then
    echo "Removing file: /userdata/system/add-ons/fightcade/Fightcade-linux-latest.tar.gz"
    rm -f "/userdata/system/add-ons/fightcade/Fightcade-linux-latest.tar.gz"
fi
if [ -f "/userdata/system/add-ons/fightcade/Fightcade/emulator/json.zip" ]; then
    echo "Removing file: /userdata/system/add-ons/fightcade/Fightcade/emulator/json.zip"
    rm -f "/userdata/system/add-ons/fightcade/Fightcade/emulator/json.zip"
fi
if [ -f "/userdata/system/add-ons/fightcade/extra/sym_wine.sh" ]; then
    echo "Removing file: /userdata/system/add-ons/fightcade/extra/sym_wine.sh"
    rm -f "/userdata/system/add-ons/fightcade/extra/sym_wine.sh"
fi
if [ -f "/userdata/system/add-ons/fightcade/usr/bin/wine" ]; then
    echo "Removing file: /userdata/system/add-ons/fightcade/usr/bin/wine"
    rm -f "/userdata/system/add-ons/fightcade/usr/bin/wine"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/fightcade/usr/bin" ]; then
    echo "Removing directory: /userdata/system/add-ons/fightcade/usr/bin"
    rm -rf "/userdata/system/add-ons/fightcade/usr/bin"
fi
if [ -d "/userdata/system/add-ons/fightcade/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/fightcade/extra"
    rm -rf "/userdata/system/add-ons/fightcade/extra"
fi
if [ -d "/userdata/system/add-ons/fightcade" ]; then
    echo "Removing directory: /userdata/system/add-ons/fightcade"
    rm -rf "/userdata/system/add-ons/fightcade"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: FIGHTCADE"
echo "========================================="
