#!/bin/bash
# Uninstaller for NVIDIAPATCHER
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: NVIDIAPATCHER"
echo "========================================="
echo ""

echo ""
echo "========================================="
echo "Uninstallation complete: NVIDIAPATCHER"
echo "========================================="
