#!/bin/bash
# Uninstaller for TELEGRAF
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: TELEGRAF"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/add-ons/telegraf" ]; then
    echo "Removing file: /userdata/add-ons/telegraf"
    rm -f "/userdata/add-ons/telegraf"
fi
if [ -f "/userdata/add-ons/telegraf/etc/telegraf" ]; then
    echo "Removing file: /userdata/add-ons/telegraf/etc/telegraf"
    rm -f "/userdata/add-ons/telegraf/etc/telegraf"
fi
if [ -f "/userdata/add-ons/telegraf/etc/telegraf/telegraf.conf.default" ]; then
    echo "Removing file: /userdata/add-ons/telegraf/etc/telegraf/telegraf.conf.default"
    rm -f "/userdata/add-ons/telegraf/etc/telegraf/telegraf.conf.default"
fi
if [ -f "/userdata/add-ons/telegraf/telegraf" ]; then
    echo "Removing file: /userdata/add-ons/telegraf/telegraf"
    rm -f "/userdata/add-ons/telegraf/telegraf"
fi
if [ -f "/userdata/system/services/telegraf" ]; then
    echo "Removing file: /userdata/system/services/telegraf"
    rm -f "/userdata/system/services/telegraf"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/add-ons/telegraf/etc/telegraf/telegraf.d" ]; then
    echo "Removing directory: /userdata/add-ons/telegraf/etc/telegraf/telegraf.d"
    rm -rf "/userdata/add-ons/telegraf/etc/telegraf/telegraf.d"
fi
if [ -d "/userdata/add-ons/telegraf/log" ]; then
    echo "Removing directory: /userdata/add-ons/telegraf/log"
    rm -rf "/userdata/add-ons/telegraf/log"
fi
if [ -d "/userdata/temp-telegraf" ]; then
    echo "Removing directory: /userdata/temp-telegraf"
    rm -rf "/userdata/temp-telegraf"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: TELEGRAF"
echo "========================================="
