#!/bin/bash
# Uninstaller for WINE-MANAGER
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: WINE-MANAGER"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/temp/batocera_wine_manager.desktop" ]; then
    echo "Removing desktop file: /userdata/system/temp/batocera_wine_manager.desktop"
    rm -f "/userdata/system/temp/batocera_wine_manager.desktop"
fi

# Remove installed files
if [ -f "/userdata/roms/ports/disable_redist_install.sh" ]; then
    echo "Removing file: /userdata/roms/ports/disable_redist_install.sh"
    rm -f "/userdata/roms/ports/disable_redist_install.sh"
fi
if [ -f "/userdata/roms/ports/enable_redist_install.sh" ]; then
    echo "Removing file: /userdata/roms/ports/enable_redist_install.sh"
    rm -f "/userdata/roms/ports/enable_redist_install.sh"
fi
if [ -f "/userdata/roms/ports/images/batocera_wine_manager.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/batocera_wine_manager.png"
    rm -f "/userdata/roms/ports/images/batocera_wine_manager.png"
fi
if [ -f "/userdata/roms/ports/wine_manager.sh" ]; then
    echo "Removing file: /userdata/roms/ports/wine_manager.sh"
    rm -f "/userdata/roms/ports/wine_manager.sh"
fi
if [ -f "/userdata/roms/ports/wine_manager.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/wine_manager.sh.keys"
    rm -f "/userdata/roms/ports/wine_manager.sh.keys"
fi
if [ -f "/userdata/system/temp/batocera_wine_manager.desktop" ]; then
    echo "Removing file: /userdata/system/temp/batocera_wine_manager.desktop"
    rm -f "/userdata/system/temp/batocera_wine_manager.desktop"
fi
if [ -f "/userdata/system/temp/batocera_wine_manager.zip" ]; then
    echo "Removing file: /userdata/system/temp/batocera_wine_manager.zip"
    rm -f "/userdata/system/temp/batocera_wine_manager.zip"
fi
if [ -f "/usr/share/applications" ]; then
    echo "Removing file: /usr/share/applications"
    rm -f "/usr/share/applications"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/temp" ]; then
    echo "Removing directory: /userdata/system/temp"
    rm -rf "/userdata/system/temp"
fi
if [ -d "/userdata/system/wine_manager" ]; then
    echo "Removing directory: /userdata/system/wine_manager"
    rm -rf "/userdata/system/wine_manager"
fi
echo ""
echo "========================================="
echo "Uninstallation complete: WINE-MANAGER"
echo "========================================="
