#!/bin/bash
# Uninstaller for PARSEC
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: PARSEC"
echo "========================================="
echo ""

# Uninstall Flatpak applications
if flatpak list --app | grep -q "com.parsecgaming.parsec" 2>/dev/null; then
    echo "Uninstalling Flatpak app: com.parsecgaming.parsec"
    flatpak uninstall -y com.parsecgaming.parsec 2>/dev/null || true
fi

# Remove installed files
if [ -f "/userdata/roms/ports/Parsec.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Parsec.sh"
    rm -f "/userdata/roms/ports/Parsec.sh"
fi
if [ -f "/userdata/roms/ports/images/parsec.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/parsec.png"
    rm -f "/userdata/roms/ports/images/parsec.png"
fi
if [ -f "/userdata/system/add-ons/parsec/launcher" ]; then
    echo "Removing file: /userdata/system/add-ons/parsec/launcher"
    rm -f "/userdata/system/add-ons/parsec/launcher"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/parsec" ]; then
    echo "Removing directory: /userdata/system/add-ons/parsec"
    rm -rf "/userdata/system/add-ons/parsec"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: PARSEC"
echo "========================================="
