#!/bin/bash
# Uninstaller for HEROIC
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: HEROIC"
echo "========================================="
echo ""

# Remove desktop files
if [ -f "/userdata/system/configs/heroic/heroic.desktop" ]; then
    echo "Removing desktop file: /userdata/system/configs/heroic/heroic.desktop"
    rm -f "/userdata/system/configs/heroic/heroic.desktop"
fi
if [ -f "/usr/share/applications/heroic.desktop" ]; then
    echo "Removing desktop file: /usr/share/applications/heroic.desktop"
    rm -f "/usr/share/applications/heroic.desktop"
fi

# Remove AppImage files
if [ -f "/userdata/system/add-ons/heroic/heroic.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/heroic/heroic.AppImage"
    rm -f "/userdata/system/add-ons/heroic/heroic.AppImage"
fi

# Clean up custom.sh entries for HEROIC

# Remove installed files
if [ -f "/userdata/system/add-ons/heroic/Launcher" ]; then
    echo "Removing file: /userdata/system/add-ons/heroic/Launcher"
    rm -f "/userdata/system/add-ons/heroic/Launcher"
fi
if [ -f "/userdata/system/add-ons/heroic/SystemLauncher" ]; then
    echo "Removing file: /userdata/system/add-ons/heroic/SystemLauncher"
    rm -f "/userdata/system/add-ons/heroic/SystemLauncher"
fi
if [ -f "/userdata/system/configs/emulationstation/es_systems_heroic.cfg" ]; then
    echo "Removing file: /userdata/system/configs/emulationstation/es_systems_heroic.cfg"
    rm -f "/userdata/system/configs/emulationstation/es_systems_heroic.cfg"
fi
if [ -f "/userdata/system/configs/heroic/heroic.desktop" ]; then
    echo "Removing file: /userdata/system/configs/heroic/heroic.desktop"
    rm -f "/userdata/system/configs/heroic/heroic.desktop"
fi
if [ -f "/userdata/system/configs/heroic/restore_desktop_entry.sh" ]; then
    echo "Removing file: /userdata/system/configs/heroic/restore_desktop_entry.sh"
    rm -f "/userdata/system/configs/heroic/restore_desktop_entry.sh"
fi
if [ -f "/usr/share/applications/heroic.desktop" ]; then
    echo "Removing file: /usr/share/applications/heroic.desktop"
    rm -f "/usr/share/applications/heroic.desktop"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/heroic/extra" ]; then
    echo "Removing directory: /userdata/system/add-ons/heroic/extra"
    rm -rf "/userdata/system/add-ons/heroic/extra"
fi
if [ -d "/userdata/system/add-ons/heroic" ]; then
    echo "Removing directory: /userdata/system/add-ons/heroic"
    rm -rf "/userdata/system/add-ons/heroic"
fi
if [ -d "/userdata/system/configs/heroic" ]; then
    echo "Removing directory: /userdata/system/configs/heroic"
    rm -rf "/userdata/system/configs/heroic"
fi
if [ -d "/userdata/roms/heroic" ]; then
    echo "Removing directory: /userdata/roms/heroic"
    rm -rf "/userdata/roms/heroic"
fi

# Update desktop database

echo ""
echo "========================================="
echo "Uninstallation complete: HEROIC"
echo "========================================="
