#!/bin/bash
# Uninstaller for SUNSHINE
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: SUNSHINE"
echo "========================================="
echo ""

# Remove AppImage files
if [ -f "/userdata/system/add-ons/sunshine/sunshine.AppImage" ]; then
    echo "Removing AppImage: /userdata/system/add-ons/sunshine/sunshine.AppImage"
    rm -f "/userdata/system/add-ons/sunshine/sunshine.AppImage"
fi

# Remove installed files
if [ -f "/userdata/system/add-ons/sunshine/sunshine.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/sunshine/sunshine.AppImage"
    rm -f "/userdata/system/add-ons/sunshine/sunshine.AppImage"
fi
if [ -f "/userdata/system/services/sunshine" ]; then
    echo "Removing file: /userdata/system/services/sunshine"
    rm -f "/userdata/system/services/sunshine"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/sunshine" ]; then
    echo "Removing directory: /userdata/system/add-ons/sunshine"
    rm -rf "/userdata/system/add-ons/sunshine"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: SUNSHINE"
echo "========================================="
