#!/bin/bash
# Uninstaller for WINCONFIG-WINDOWS-GAME-FIX
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: WINCONFIG-WINDOWS-GAME-FIX"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/tmp/gamelistconfig.sh" ]; then
    echo "Removing file: /tmp/gamelistconfig.sh"
    rm -f "/tmp/gamelistconfig.sh"
fi
if [ -f "/userdata/roms/ports/Fix.sh")" ]; then
    echo "Removing file: /userdata/roms/ports/Fix.sh")"
    rm -f "/userdata/roms/ports/Fix.sh")"
fi
if [ -f "/userdata/tmp/Winconfig/Winconfig.DRL" ]; then
    echo "Removing file: /userdata/tmp/Winconfig/Winconfig.DRL"
    rm -f "/userdata/tmp/Winconfig/Winconfig.DRL"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/tmp/Winconfig/extracted" ]; then
    echo "Removing directory: /userdata/tmp/Winconfig/extracted"
    rm -rf "/userdata/tmp/Winconfig/extracted"
fi
if [ -d "/userdata/tmp/Winconfig" ]; then
    echo "Removing directory: /userdata/tmp/Winconfig"
    rm -rf "/userdata/tmp/Winconfig"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: WINCONFIG-WINDOWS-GAME-FIX"
echo "========================================="
