#!/bin/bash
# Uninstaller for FREEJ2ME
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: FREEJ2ME"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/tmp/Freej2me/Freej2me.DRL" ]; then
    echo "Removing file: /userdata/tmp/Freej2me/Freej2me.DRL"
    rm -f "/userdata/tmp/Freej2me/Freej2me.DRL"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/tmp/Freej2me/extracted" ]; then
    echo "Removing directory: /userdata/tmp/Freej2me/extracted"
    rm -rf "/userdata/tmp/Freej2me/extracted"
fi
if [ -d "/userdata/tmp/Freej2me" ]; then
    echo "Removing directory: /userdata/tmp/Freej2me"
    rm -rf "/userdata/tmp/Freej2me"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: FREEJ2ME"
echo "========================================="
