#!/bin/bash
# Uninstaller for CELESTE64
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: CELESTE64"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/roms/ports/Celeste64.sh" ]; then
    echo "Removing file: /userdata/roms/ports/Celeste64.sh"
    rm -f "/userdata/roms/ports/Celeste64.sh"
fi
if [ -f "/userdata/roms/ports/images/celeste64-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/celeste64-logo.png"
    rm -f "/userdata/roms/ports/images/celeste64-logo.png"
fi
if [ -f "/userdata/system/add-ons/celeste64/celeste64.zip" ]; then
    echo "Removing file: /userdata/system/add-ons/celeste64/celeste64.zip"
    rm -f "/userdata/system/add-ons/celeste64/celeste64.zip"
fi
    echo "Removing file: latest"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/celeste64/" ]; then
    echo "Removing directory: /userdata/system/add-ons/celeste64/"
    rm -rf "/userdata/system/add-ons/celeste64/"
fi
if [ -d "/userdata/system/add-ons/celeste64" ]; then
    echo "Removing directory: /userdata/system/add-ons/celeste64"
    rm -rf "/userdata/system/add-ons/celeste64"
fi
fi

echo ""
echo "========================================="
echo "Uninstallation complete: CELESTE64"
echo "========================================="
