#!/bin/bash
# Uninstaller for DARK-MODE
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: DARK-MODE"
echo "========================================="
echo ""

# Remove installed files
if [ -f "/userdata/system/add-ons/darkmode/Adwaita-dark.zip" ]; then
    echo "Removing file: /userdata/system/add-ons/darkmode/Adwaita-dark.zip"
    rm -f "/userdata/system/add-ons/darkmode/Adwaita-dark.zip"
fi
if [ -f "/userdata/system/services/dark_mode" ]; then
    echo "Removing file: /userdata/system/services/dark_mode"
    rm -f "/userdata/system/services/dark_mode"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/darkmode" ]; then
    echo "Removing directory: /userdata/system/add-ons/darkmode"
    rm -rf "/userdata/system/add-ons/darkmode"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: DARK-MODE"
echo "========================================="
