#!/bin/bash
# Uninstaller for DESKTOP
# Generated by BUA Uninstaller Generator
# This is a standalone script - no variables or external dependencies

echo "========================================="
echo "Uninstalling: DESKTOP"
echo "========================================="
echo ""

# Stop and remove Docker containers
if docker ps -a --format '{{.Names}}' | grep -q "^desktop$" 2>/dev/null; then
    echo "Stopping Docker container: desktop"
    docker stop "desktop" 2>/dev/null || true
    echo "Removing Docker container: desktop"
    docker rm "desktop" 2>/dev/null || true
fi

# Remove installed files
if [ -f "/userdata/roms/ports/BatoDesktop.sh" ]; then
    echo "Removing file: /userdata/roms/ports/BatoDesktop.sh"
    rm -f "/userdata/roms/ports/BatoDesktop.sh"
fi
if [ -f "/userdata/roms/ports/BatoDesktop.sh.keys" ]; then
    echo "Removing file: /userdata/roms/ports/BatoDesktop.sh.keys"
    rm -f "/userdata/roms/ports/BatoDesktop.sh.keys"
fi
if [ -f "/userdata/roms/ports/images/desktop-logo.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/desktop-logo.png"
    rm -f "/userdata/roms/ports/images/desktop-logo.png"
fi
if [ -f "/userdata/roms/ports/images/desktop-marquee.png" ]; then
    echo "Removing file: /userdata/roms/ports/images/desktop-marquee.png"
    rm -f "/userdata/roms/ports/images/desktop-marquee.png"
fi
if [ -f "/userdata/system/add-ons/desktop/Desktop.AppImage" ]; then
    echo "Removing file: /userdata/system/add-ons/desktop/Desktop.AppImage"
    rm -f "/userdata/system/add-ons/desktop/Desktop.AppImage"
fi

# Remove created directories (deepest first)
if [ -d "/userdata/system/add-ons/desktop" ]; then
    echo "Removing directory: /userdata/system/add-ons/desktop"
    rm -rf "/userdata/system/add-ons/desktop"
fi

echo ""
echo "========================================="
echo "Uninstallation complete: DESKTOP"
echo "========================================="
